In [1]:
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import Ridge

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# Load datasets
stints_2023 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2023/stints_clean.csv")
stints_2024 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2024/stints_2024.csv")

# Combine seasons
combined_stints = pd.concat(
    [stints_2023, stints_2024],
    ignore_index=True
)

# Feature engineering
model_df = combined_stints.copy()

model_df["GP_Stint"] = (
    model_df["GP"]
    + "_S"
    + model_df["Stint"].astype(str)
)

model_df["Compound_Stint"] = (
    model_df["Compound"]
    + "_S"
    + model_df["Stint"].astype(str)
)

# Features and target
X = model_df[
    [
        "GP",
        "Compound",
        "Stint",
        "GP_Stint",
        "Compound_Stint"
    ]
]

y = model_df["StintLength"]

# Pipeline
categorical_features = [
    "GP",
    "Compound",
    "Stint",
    "GP_Stint",
    "Compound_Stint"
]

preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        )
    ]
)

model = Pipeline([
    ("preprocess", preprocessor),
    ("regressor", Ridge(alpha=1.0))
])

# Train / Test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train
model.fit(
    X_train,
    y_train
)

# Evaluate
preds = model.predict(X_test)

mae = mean_absolute_error(
    y_test,
    preds
)

print("Combined Dataset MAE:", mae)
print("Total stints:", len(model_df))

Combined Dataset MAE: 6.282319064752515
Total stints: 2427

In [21]:
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import Ridge

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# ==========================
# Load datasets
# ==========================

stints_2023 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2023/stints_clean.csv")
stints_2024 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2024/stints_2024.csv")


# Add season labels
stints_2023["Season"] = "2023"
stints_2024["Season"] = "2024"

# Combine seasons
combined_stints = pd.concat(
    [stints_2023, stints_2024],
    ignore_index=True
)

print("Combined stints:", combined_stints.shape)

# ==========================
# Feature Engineering
# ==========================

model_df = combined_stints.copy()

model_df["GP_Stint"] = (
    model_df["GP"]
    + "_S"
    + model_df["Stint"].astype(str)
)

model_df["Compound_Stint"] = (
    model_df["Compound"].astype(str)
    + "_S"
    + model_df["Stint"].astype(str)
)

# ==========================
# Features and Target
# ==========================

X = model_df[
    [
        "GP",
        "Compound",
        "Stint",
        "GP_Stint",
        "Compound_Stint",
        "Season"
    ]
]

y = model_df["StintLength"]

# ==========================
# Preprocessing
# ==========================

categorical_features = [
    "GP",
    "Compound",
    "Stint",
    "GP_Stint",
    "Compound_Stint",
    "Season"
]

preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        )
    ]
)

# ==========================
# Model
# ==========================

model = Pipeline([
    ("preprocess", preprocessor),
    ("regressor", Ridge(alpha=1.0))
])

# ==========================
# Train/Test Split
# ==========================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# ==========================
# Training
# ==========================

model.fit(
    X_train,
    y_train
)

# ==========================
# Evaluation
# ==========================

preds = model.predict(X_test)

mae = mean_absolute_error(
    y_test,
    preds
)

print("\n===== Phase 2B.1 Results =====")
print(f"MAE with Season Feature: {mae:.4f}")
print("Previous MAE: 6.2823")
print(f"Delta: {mae - 6.2823:.4f}")

Combined stints: (2427, 6)

===== Phase 2B.1 Results =====
MAE with Season Feature: 6.2012
Previous MAE: 6.2823
Delta: -0.0811

#### Weather-Feature Testing

In [6]:
#2023 
import pandas as pd

merged_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/final_merged_2023_data.csv"
)

weather_stints_2023 = (
    merged_2023
    .groupby(
        ["GP", "Driver", "Stint"]
    )[
        ["AirTemp", "TrackTemp"]
    ]
    .mean()
    .reset_index()
)

print(weather_stints_2023.shape)
weather_stints_2023.head()

(2216, 5)

C:\Users\VANSH\AppData\Local\Temp\ipykernel_12672\1084341378.py:4: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_2023 = pd.read_csv(

                     GP Driver  Stint  AirTemp  TrackTemp
0  Abu Dhabi Grand Prix    ALB      1      NaN        NaN
1  Abu Dhabi Grand Prix    ALB      2      NaN        NaN
2  Abu Dhabi Grand Prix    ALB      3      NaN        NaN
3  Abu Dhabi Grand Prix    ALB      4      NaN        NaN
4  Abu Dhabi Grand Prix    ALB      5      NaN        NaN

In [8]:
#2024
merged_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/final_merged_2024_data.csv"
)

weather_stints_2024 = (
    merged_2024
    .groupby(
        ["GP", "Driver", "Stint"]
    )[
        ["AirTemp", "TrackTemp"]
    ]
    .mean()
    .reset_index()
)

print(weather_stints_2024.shape)
weather_stints_2024.head()

(2000, 5)

                     GP Driver  Stint    AirTemp  TrackTemp
0  Abu Dhabi Grand Prix    ALB      1  26.875000  31.766667
1  Abu Dhabi Grand Prix    ALB      2  26.288889  30.377778
2  Abu Dhabi Grand Prix    ALO      1  26.876923  31.723077
3  Abu Dhabi Grand Prix    ALO      2  26.504167  30.895833
4  Abu Dhabi Grand Prix    ALO      3  26.014286  29.704762

In [9]:
#weather_stint_dataset merge
stints_2023 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2023/stints_clean.csv")
stints_2024 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2024/stints_2024.csv")

stints_2023_weather = stints_2023.copy()
stints_2024_weather = stints_2024.copy()

stints_2023_weather.to_csv(
    "stints_2023_weather.csv",
    index=False
)

stints_2024_weather.to_csv(
    "stints_2024_weather.csv",
    index=False
)

In [14]:
#2023
stints_2023 = pd.read_csv("C:/Users/VANSH/Formula1/notebooks/stints_2023_weather.csv")

stints_2023_weather = stints_2023.merge(
    weather_stints_2023,
    on=["GP", "Driver", "Stint"],
    how="left"
)
print(stints_2023_weather.shape)
stints_2023_weather.head()
stints_2023_weather.to_csv(
    "stints_2023_weather.csv", index=False)

(1198, 7)

In [ ]:
#2024
stints_2024 = pd.read_csv("C:/Users/VANSH/Formula1/notebooks/stints_2024_weather.csv")

stints_2024_weather = stints_2024.merge(
    weather_stints_2024,
    on=["GP", "Driver", "Stint"],
    how="left"
)
print(stints_2024_weather.shape)
stints_2024_weather.head()
stints_2024_weather.to_csv(
    "stints_2024_weather.csv", index=False)
print("Weather data merged and saved for both seasons.")

(1229, 7)
Weather data merged and saved for both seasons.

In [16]:
print(
    stints_2023_weather[
        ["AirTemp", "TrackTemp"]
    ]
    .isna()
    .sum()
)

print(
    stints_2024_weather[
        ["AirTemp", "TrackTemp"]
    ]
    .isna()
    .sum()
)

AirTemp      0
TrackTemp    0
dtype: int64
AirTemp      0
TrackTemp    0
dtype: int64

In [ ]:
stints_2023_weather["Season"] = "2023"
stints_2024_weather["Season"] = "2024"

combined_stints = pd.concat(
    [
        stints_2023_weather,
        stints_2024_weather
    ],
    ignore_index=True
)

In [12]:
stints_2024 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2024/stints_2024_weather.csv")
stints_2024["Compound"].value_counts()

Compound
HARD            511
MEDIUM          465
SOFT            141
INTERMEDIATE    105
WET               7
Name: count, dtype: int64

In [18]:
weather_df_2024 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2024/cleaned_weather_2024.csv")
weather_df_2024.columns

Index(['Time', 'AirTemp', 'Humidity', 'Pressure', 'Rainfall', 'TrackTemp',
       'WindDirection', 'WindSpeed', 'RoundNumber', 'EventName', 'Session',
       'Date'],
      dtype='object')

In [19]:
weather_df_2023 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2023/weather_2023_cleaned.csv")
weather_df_2023.columns

Index(['Time', 'AirTemp', 'Humidity', 'Pressure', 'Rainfall', 'TrackTemp',
       'WindDirection', 'WindSpeed', 'RoundNumber', 'EventName', 'Session',
       'Date'],
      dtype='object')

In [20]:
print(weather_df_2023["Rainfall"].value_counts(dropna=False))
print(weather_df_2024["Rainfall"].value_counts(dropna=False))

Rainfall
False    9447
True      579
Name: count, dtype: int64
Rainfall
False    6936
True      481
Name: count, dtype: int64

In [26]:
stints_2023 = pd.read_csv("stints_2023_weather.csv")
stints_2024 = pd.read_csv("stints_2024_weather.csv")

combined_stints = pd.concat(
    [stints_2023, stints_2024],
    ignore_index=True
)

model_df = combined_stints.copy()
model_df.columns

Index(['GP', 'Driver', 'Stint', 'Compound', 'StintLength', 'AirTemp',
       'TrackTemp'],
      dtype='object')

In [1]:
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import Ridge

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# Load weather-enhanced stint datasets
stints_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_2023_weather.csv"
)

stints_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_2024_weather.csv"
)


stints_2023["Season"] = 2023
stints_2024["Season"] = 2024

# Combine seasons
combined_stints = pd.concat(
    [stints_2023, stints_2024],
    ignore_index=True
)

# Feature engineering
model_df = combined_stints.copy()

model_df["GP_Stint"] = (
    model_df["GP"]
    + "_S"
    + model_df["Stint"].astype(str)
)

model_df["Compound_Stint"] = (
    model_df["Compound"]
    + "_S"
    + model_df["Stint"].astype(str)
)

# Features and target
X = model_df[
    [
        "GP",
        "Compound",
        "Stint",
        "GP_Stint",
        "Compound_Stint",
        "Season",
        "AirTemp",
        "TrackTemp"
    ]
]

y = model_df["StintLength"]

# Feature groups
categorical_features = [
    "GP",
    "Compound",
    "Stint",
    "GP_Stint",
    "Compound_Stint"
]

numerical_features = [
    "Season",
    "AirTemp",
    "TrackTemp"
]

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numerical_features
        )
    ]
)

# Model
model = Pipeline([
    ("preprocess", preprocessor),
    ("regressor", Ridge(alpha=1.0))
])

# Train / Test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train
model.fit(
    X_train,
    y_train
)

# Predict
preds = model.predict(X_test)

# Evaluate
mae = mean_absolute_error(
    y_test,
    preds
)

print("Combined Dataset MAE with both TrackTemp and AirTemp: ", mae)
print("Total stints:", len(model_df))

Combined Dataset MAE with both TrackTemp and AirTemp:  6.143372292968852
Total stints: 2427

In [2]:
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import Ridge

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# Load weather-enhanced stint datasets
stints_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_2023_weather.csv"
)

stints_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_2024_weather.csv"
)
stints_2023["Season"] = 2023
stints_2024["Season"] = 2024

# Combine seasons
combined_stints = pd.concat(
    [stints_2023, stints_2024],
    ignore_index=True
)

# Feature engineering
model_df = combined_stints.copy()

model_df["GP_Stint"] = (
    model_df["GP"]
    + "_S"
    + model_df["Stint"].astype(str)
)

model_df["Compound_Stint"] = (
    model_df["Compound"]
    + "_S"
    + model_df["Stint"].astype(str)
)

# Features and target
X = model_df[
    [
        "GP",
        "Compound",
        "Stint",
        "GP_Stint",
        "Compound_Stint",
        "Season",
        "TrackTemp"
    ]
]

y = model_df["StintLength"]

# Feature groups
categorical_features = [
    "GP",
    "Compound",
    "Stint",
    "GP_Stint",
    "Compound_Stint"
]

numerical_features = [
    "Season",
    "TrackTemp"
]

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numerical_features
        )
    ]
)

# Model
model = Pipeline([
    ("preprocess", preprocessor),
    ("regressor", Ridge(alpha=1.0))
])

# Train / Test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train
model.fit(
    X_train,
    y_train
)

# Predict
preds = model.predict(X_test)

# Evaluate
mae = mean_absolute_error(
    y_test,
    preds
)

print("Combined Dataset MAE with TrackTemp only: ", mae)
print("Total stints:", len(model_df))

Combined Dataset MAE with TrackTemp only:  6.172989315907902
Total stints: 2427

In [8]:
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import Ridge

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# Load weather-enhanced stint datasets
stints_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_2023_weather.csv"
)

stints_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_2024_weather.csv"
)
stints_2023["Season"] = 2023
stints_2024["Season"] = 2024

# Combine seasons
combined_stints = pd.concat(
    [stints_2023, stints_2024],
    ignore_index=True
)

# Feature engineering
model_df = combined_stints.copy()

model_df["GP_Stint"] = (
    model_df["GP"]
    + "_S"
    + model_df["Stint"].astype(str)
)

model_df["Compound_Stint"] = (
    model_df["Compound"]
    + "_S"
    + model_df["Stint"].astype(str)
)

# Features and target
X = model_df[
    [
        "GP",
        "Compound",
        "Stint",
        "GP_Stint",
        "Compound_Stint",
        "Season",
        "AirTemp"
    ]
]

y = model_df["StintLength"]

# Feature groups
categorical_features = [
    "GP",
    "Compound",
    "Stint",
    "GP_Stint",
    "Compound_Stint"
]

numerical_features = [
    "Season",
    "AirTemp"
]

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numerical_features
        )
    ]
)

# Model
model = Pipeline([
    ("preprocess", preprocessor),
    ("regressor", Ridge(alpha=1.0))
])

# Train / Test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train
model.fit(
    X_train,
    y_train
)

# Predict
preds = model.predict(X_test)

# Evaluate
mae = mean_absolute_error(
    y_test,
    preds
)

print("Combined Dataset MAE with AirTemp only: ", mae)
print("Total stints:", len(model_df))

Combined Dataset MAE with AirTemp only:  6.215521531462013
Total stints: 2427

#### To check rainy GPs in 2023 and 2024

In [3]:
import pandas as pd

weather_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/weather_2023_cleaned.csv"
)

weather_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/cleaned_weather_2024.csv"
)

combined_weather = pd.concat(
    [weather_2023, weather_2024],
    ignore_index=True
)

rain_summary = (
    combined_weather
    .groupby("EventName")["Rainfall"]
    .sum()
    .reset_index()
    .sort_values("Rainfall", ascending=False)
)

print(rain_summary)

                    EventName  Rainfall
7         Canadian Grand Prix       210
6          British Grand Prix       192
11       Hungarian Grand Prix       133
22       São Paulo Grand Prix       122
5          Belgian Grand Prix       100
9            Dutch Grand Prix        98
21         Spanish Grand Prix        75
1       Australian Grand Prix        47
17          Monaco Grand Prix        33
13        Japanese Grand Prix        26
15     Mexico City Grand Prix        18
2         Austrian Grand Prix         4
23   United States Grand Prix         2
20       Singapore Grand Prix         0
19   Saudi Arabian Grand Prix         0
18           Qatar Grand Prix         0
0        Abu Dhabi Grand Prix         0
16           Miami Grand Prix         0
14       Las Vegas Grand Prix         0
10  Emilia Romagna Grand Prix         0
8          Chinese Grand Prix         0
4          Bahrain Grand Prix         0
3       Azerbaijan Grand Prix         0
12         Italian Grand Prix         0

In [4]:
race_weather = (
    combined_weather
    .groupby("EventName")
    .agg(
        RainySamples=("Rainfall", "sum"),
        TotalSamples=("Rainfall", "count")
    )
)

race_weather["RainPct"] = (
    race_weather["RainySamples"]
    / race_weather["TotalSamples"]
    * 100
)

race_weather = race_weather.sort_values(
    "RainPct",
    ascending=False
)

print(
    race_weather[
        ["RainySamples", "TotalSamples", "RainPct"]
    ]
)

                           RainySamples  TotalSamples    RainPct
EventName
Canadian Grand Prix                 210           928  22.629310
São Paulo Grand Prix                122           550  22.181818
Belgian Grand Prix                  100           470  21.276596
British Grand Prix                  192           964  19.917012
Dutch Grand Prix                     98           706  13.881020
Hungarian Grand Prix                133          1057  12.582781
Spanish Grand Prix                   75           960   7.812500
Australian Grand Prix                47          1011   4.648863
Monaco Grand Prix                    33          1001   3.296703
Mexico City Grand Prix               18           670   2.686567
Japanese Grand Prix                  26           993   2.618328
Austrian Grand Prix                   4           620   0.645161
United States Grand Prix              2           484   0.413223
Singapore Grand Prix                  0           693   0.000000
Saudi Arabian Grand Prix              0           970   0.000000
Qatar Grand Prix                      0           475   0.000000
Abu Dhabi Grand Prix                  0           626   0.000000
Miami Grand Prix                      0           791   0.000000
Las Vegas Grand Prix                  0           582   0.000000
Emilia Romagna Grand Prix             0           453   0.000000
Chinese Grand Prix                    0           333   0.000000
Bahrain Grand Prix                    0           991   0.000000
Azerbaijan Grand Prix                 0           501   0.000000
Italian Grand Prix                    0           614   0.000000

In [5]:
race_weather = combined_weather[
    combined_weather["Session"] == "R"
].copy()

race_weather = (
    race_weather
    .groupby("EventName")
    .agg(
        RainySamples=("Rainfall", "sum"),
        TotalSamples=("Rainfall", "count")
    )
)

race_weather["RainPct"] = (
    race_weather["RainySamples"]
    / race_weather["TotalSamples"]
    * 100
)

race_weather = race_weather.sort_values(
    "RainPct",
    ascending=False
)

print(race_weather)

                           RainySamples  TotalSamples    RainPct
EventName
São Paulo Grand Prix                118           384  30.729167
British Grand Prix                   51           298  17.114094
Dutch Grand Prix                     48           362  13.259669
Canadian Grand Prix                  31           275  11.272727
Monaco Grand Prix                    26           376   6.914894
Belgian Grand Prix                   11           287   3.832753
Austrian Grand Prix                   4           296   1.351351
Spanish Grand Prix                    1           308   0.324675
Abu Dhabi Grand Prix                  0           304   0.000000
Mexico City Grand Prix                0           349   0.000000
Singapore Grand Prix                  0           336   0.000000
Saudi Arabian Grand Prix              0           294   0.000000
Qatar Grand Prix                      0           310   0.000000
Miami Grand Prix                      0           305   0.000000
Italian Grand Prix                    0           289   0.000000
Las Vegas Grand Prix                  0           251   0.000000
Japanese Grand Prix                   0           339   0.000000
Australian Grand Prix                 0           366   0.000000
Hungarian Grand Prix                  0           319   0.000000
Emilia Romagna Grand Prix             0           143   0.000000
Chinese Grand Prix                    0           165   0.000000
Bahrain Grand Prix                    0           318   0.000000
Azerbaijan Grand Prix                 0           312   0.000000
United States Grand Prix              0           323   0.000000

#### Dry Races MAE

In [6]:
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import Ridge

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# Load weather-enhanced stint datasets
stints_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_weather_2023.csv"
)

stints_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_weather_2024.csv"
)

# Add season feature
stints_2023["Season"] = 2023
stints_2024["Season"] = 2024

# Combine seasons
combined_stints = pd.concat(
    [stints_2023, stints_2024],
    ignore_index=True
)

# Feature engineering
model_df = combined_stints.copy()

model_df["GP_Stint"] = (
    model_df["GP"]
    + "_S"
    + model_df["Stint"].astype(str)
)

model_df["Compound_Stint"] = (
    model_df["Compound"]
    + "_S"
    + model_df["Stint"].astype(str)
)

# Wet races identified from Race-session RainPct > 5%
wet_races = [
    "São Paulo Grand Prix",
    "British Grand Prix",
    "Dutch Grand Prix",
    "Canadian Grand Prix",
    "Monaco Grand Prix"
]

# Create dry-only dataset
dry_df = model_df[
    ~model_df["GP"].isin(wet_races)
].copy()

print("Original stints:", len(model_df))
print("Dry-only stints:", len(dry_df))

# Features and target
X = dry_df[
    [
        "GP",
        "Compound",
        "Stint",
        "GP_Stint",
        "Compound_Stint",
        "Season",
        "AirTemp",
        "TrackTemp"
    ]
]

y = dry_df["StintLength"]

# Feature groups
categorical_features = [
    "GP",
    "Compound",
    "Stint",
    "GP_Stint",
    "Compound_Stint"
]

numerical_features = [
    "Season",
    "AirTemp",
    "TrackTemp"
]

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numerical_features
        )
    ]
)

# Model
model = Pipeline([
    ("preprocess", preprocessor),
    ("regressor", Ridge(alpha=1.0))
])

# Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train
model.fit(
    X_train,
    y_train
)

# Predict
preds = model.predict(X_test)

# Evaluate
mae = mean_absolute_error(
    y_test,
    preds
)

print("Dry-Only Dataset MAE:", mae)

Original stints: 2427
Dry-only stints: 1872
Dry-Only Dataset MAE: 5.829821737045296

#### Merging weather stint & freshtyre stint

In [ ]:
#2023
import pandas as pd

weather_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_weather_2023.csv"
)

fresh_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_freshtyre_2023.csv"
)

stints_master_2023 = weather_2023.merge(
    fresh_2023[
        [
            "GP",
            "Driver",
            "Stint",
            "Compound",
            "FreshTyre"
        ]
    ],
    on=[
        "GP",
        "Driver",
        "Stint",
        "Compound"
    ],
    how="left"
)

print(stints_master_2023.shape)
print(stints_master_2023.isna().sum())

stints_master_2023.to_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_master_2023.csv",
    index=False
)

(1198, 8)
GP             0
Driver         0
Stint          0
Compound       0
StintLength    0
AirTemp        0
TrackTemp      0
FreshTyre      0
dtype: int64

In [3]:
#2024
import pandas as pd

weather_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_weather_2024.csv"
)

fresh_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_freshtyre_2024.csv"
)

stints_master_2024 = weather_2024.merge(
    fresh_2024[
        [
            "GP",
            "Driver",
            "Stint",
            "Compound",
            "FreshTyre"
        ]
    ],
    on=[
        "GP",
        "Driver",
        "Stint",
        "Compound"
    ],
    how="left"
)

print(stints_master_2024.shape)
print(stints_master_2024.isna().sum())

stints_master_2024.to_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_master_2024.csv",
    index=False
)

(1229, 8)
GP             0
Driver         0
Stint          0
Compound       0
StintLength    0
AirTemp        0
TrackTemp      0
FreshTyre      0
dtype: int64

In [4]:
print(stints_master_2023.columns.tolist())
print(stints_master_2024.columns.tolist())

['GP', 'Driver', 'Stint', 'Compound', 'StintLength', 'AirTemp', 'TrackTemp', 'FreshTyre']
['GP', 'Driver', 'Stint', 'Compound', 'StintLength', 'AirTemp', 'TrackTemp', 'FreshTyre']

In [5]:
print(stints_master_2023["FreshTyre"].isna().sum())
print(stints_master_2024["FreshTyre"].isna().sum())

0
0

In [1]:
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import Ridge

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# Load master datasets
stints_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_master_2023.csv"
)

stints_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_master_2024.csv"
)

# Add season feature
stints_2023["Season"] = 2023
stints_2024["Season"] = 2024

# Combine seasons
combined_stints = pd.concat(
    [stints_2023, stints_2024],
    ignore_index=True
)

# Feature engineering
model_df = combined_stints.copy()

model_df["GP_Stint"] = (
    model_df["GP"]
    + "_S"
    + model_df["Stint"].astype(str)
)

model_df["Compound_Stint"] = (
    model_df["Compound"]
    + "_S"
    + model_df["Stint"].astype(str)
)

# Dry-only benchmark
wet_races = [
    "São Paulo Grand Prix",
    "British Grand Prix",
    "Dutch Grand Prix",
    "Canadian Grand Prix",
    "Monaco Grand Prix"
]

dry_df = model_df[
    ~model_df["GP"].isin(wet_races)
].copy()

print("Original stints:", len(model_df))
print("Dry-only stints:", len(dry_df))

# Features
X = dry_df[
    [
        "GP",
        "Compound",
        "Stint",
        "GP_Stint",
        "Compound_Stint",
        "Season",
        "AirTemp",
        "TrackTemp",
        "FreshTyre"
    ]
]

y = dry_df["StintLength"]

# Feature groups
categorical_features = [
    "GP",
    "Compound",
    "Stint",
    "GP_Stint",
    "Compound_Stint"
]

numerical_features = [
    "Season",
    "AirTemp",
    "TrackTemp",
    "FreshTyre"
]

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numerical_features
        )
    ]
)

# Model
model = Pipeline([
    ("preprocess", preprocessor),
    ("regressor", Ridge(alpha=1.0))
])

# Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train
model.fit(X_train, y_train)

# Predict
preds = model.predict(X_test)

# Evaluate
mae = mean_absolute_error(
    y_test,
    preds
)

print("Dry-Only + FreshTyre MAE:", mae)
print("Total stints:", len(dry_df))

Original stints: 2427
Dry-only stints: 1872
Dry-Only + FreshTyre MAE: 5.837993781054278
Total stints: 1872

#### Race_progress Feature addition (2023)

In [ ]:
import pandas as pd

# Load lap-level dataset
laps_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/final_merged_2023_data.csv"
)

# Race laps only
race_laps_2023 = laps_2023[
    laps_2023["Session"] == "R"
].copy()

# Stint start lap
stint_start_2023 = (
    race_laps_2023
    .groupby(
        ["GP", "Driver", "Stint", "Compound"],
        as_index=False
    )
    .agg(
        StintStartLap=("LapNumber", "min")
    )
)

# Total race laps per GP
race_laps_total_2023 = (
    race_laps_2023
    .groupby("GP", as_index=False)
    .agg(
        TotalRaceLaps=("LapNumber", "max")
    )
)

# Merge and calculate RaceProgress
race_progress_2023 = stint_start_2023.merge(
    race_laps_total_2023,
    on="GP",
    how="left"
)

race_progress_2023["RaceProgress"] = (
    race_progress_2023["StintStartLap"]
    / race_progress_2023["TotalRaceLaps"]
)

# Load master dataset
master_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_master_2023.csv"
)

# Merge RaceProgress
master_2023 = master_2023.merge(
    race_progress_2023[
        [
            "GP",
            "Driver",
            "Stint",
            "Compound",
            "RaceProgress"
        ]
    ],
    on=[
        "GP",
        "Driver",
        "Stint",
        "Compound"
    ],
    how="left"
)

print(master_2023.shape)
print(master_2023["RaceProgress"].isna().sum())

master_2023.to_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_master_2023.csv",
    index=False
)

C:\Users\VANSH\AppData\Local\Temp\ipykernel_22320\138132886.py:4: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  laps_2023 = pd.read_csv(

(1198, 9)
0

In [7]:
master_2023['RaceProgress'].head(10)

0    0.018519
1    0.018519
2    0.185185
3    0.018519
4    0.037037
5    0.185185
6    0.018519
7    0.185185
8    0.851852
9    0.018519
Name: RaceProgress, dtype: float64

#### Race_progress addition 2024

In [10]:
import pandas as pd

# Load lap-level dataset
laps_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/final_merged_2024_data.csv"
)

# Race laps only
race_laps_2024 = laps_2024[
    laps_2024["SessionType"] == "R"
].copy()

# Stint start lap
stint_start_2024 = (
    race_laps_2024
    .groupby(
        ["GP", "Driver", "Stint", "Compound"],
        as_index=False
    )
    .agg(
        StintStartLap=("LapNumber", "min")
    )
)

# Total race laps per GP
race_laps_total_2024 = (
    race_laps_2024
    .groupby("GP", as_index=False)
    .agg(
        TotalRaceLaps=("LapNumber", "max")
    )
)

# Merge and calculate RaceProgress
race_progress_2024 = stint_start_2024.merge(
    race_laps_total_2024,
    on="GP",
    how="left"
)

race_progress_2024["RaceProgress"] = (
    race_progress_2024["StintStartLap"]
    / race_progress_2024["TotalRaceLaps"]
)

# Load master dataset
master_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_master_2024.csv"
)

# Merge RaceProgress
master_2024 = master_2024.merge(
    race_progress_2024[
        [
            "GP",
            "Driver",
            "Stint",
            "Compound",
            "RaceProgress"
        ]
    ],
    on=[
        "GP",
        "Driver",
        "Stint",
        "Compound"
    ],
    how="left"
)

print(master_2024.shape)
print(master_2024["RaceProgress"].isna().sum())

master_2024.to_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_master_2024.csv",
    index=False
)

(1229, 9)
0

In [11]:
master_2024.head(10)

,GP,Driver,Stint,Compound,StintLength,AirTemp,TrackTemp,FreshTyre,RaceProgress
0,Abu Dhabi Grand Prix,ALB,1,MEDIUM,12,26.875000,31.766667,1,0.017241
1,Abu Dhabi Grand Prix,ALB,2,HARD,45,26.288889,30.377778,1,0.224138
2,Abu Dhabi Grand Prix,ALO,1,MEDIUM,14,26.876923,31.723077,0,0.017241
3,Abu Dhabi Grand Prix,ALO,2,HARD,25,26.504167,30.895833,0,0.241379
4,Abu Dhabi Grand Prix,ALO,3,HARD,22,26.014286,29.704762,0,0.655172
5,Abu Dhabi Grand Prix,BOT,1,MEDIUM,6,26.900000,31.883333,1,0.017241
6,Abu Dhabi Grand Prix,BOT,2,HARD,23,26.652174,31.230435,1,0.120690
7,Abu Dhabi Grand Prix,COL,1,MEDIUM,3,26.933333,31.933333,1,0.017241
8,Abu Dhabi Grand Prix,COL,2,HARD,23,26.713043,31.321739,1,0.068966
9,Abu Dhabi Grand Prix,DOO,1,MEDIUM,22,26.790909,31.550000,1,0.017241

In [2]:
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import Ridge

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# Load master datasets
stints_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_master_2023.csv"
)

stints_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_master_2024.csv"
)

# Add season feature
stints_2023["Season"] = 2023
stints_2024["Season"] = 2024

# Combine seasons
combined_stints = pd.concat(
    [stints_2023, stints_2024],
    ignore_index=True
)

# Feature engineering
model_df = combined_stints.copy()

model_df["GP_Stint"] = (
    model_df["GP"]
    + "_S"
    + model_df["Stint"].astype(str)
)

model_df["Compound_Stint"] = (
    model_df["Compound"]
    + "_S"
    + model_df["Stint"].astype(str)
)

# Dry-only benchmark
wet_races = [
    "São Paulo Grand Prix",
    "British Grand Prix",
    "Dutch Grand Prix",
    "Canadian Grand Prix",
    "Monaco Grand Prix"
]

dry_df = model_df[
    ~model_df["GP"].isin(wet_races)
].copy()

print("Original stints:", len(model_df))
print("Dry-only stints:", len(dry_df))

# Features
X = dry_df[
    [
        "GP",
        "Compound",
        "Stint",
        "GP_Stint",
        "Compound_Stint",
        "Season",
        "AirTemp",
        "TrackTemp",
        #"FreshTyre",
        "RaceProgress"
    ]
]

y = dry_df["StintLength"]

# Feature groups
categorical_features = [
    "GP",
    "Compound",
    "Stint",
    "GP_Stint",
    "Compound_Stint"
]

numerical_features = [
    "Season",
    "AirTemp",
    "TrackTemp",
    #"FreshTyre",
    "RaceProgress"
]

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numerical_features
        )
    ]
)

# Model
model = Pipeline([
    ("preprocess", preprocessor),
    ("regressor", Ridge(alpha=1.0))
])

# Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train
model.fit(X_train, y_train)

# Predict
preds = model.predict(X_test)

# Evaluate
mae = mean_absolute_error(
    y_test,
    preds
)

print("Dry-Only + FreshTyre + RaceProgress MAE:", mae)
print("Total stints:", len(dry_df))

Original stints: 2427
Dry-only stints: 1872
Dry-Only + FreshTyre + RaceProgress MAE: 5.676825382307484
Total stints: 1872

## XGBoost Baseline

In [4]:
import xgboost

print(xgboost.__version__)

3.2.0

In [8]:
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# Load master datasets
stints_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/stints_master_2023.csv"
)

stints_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/stints_master_2024.csv"
)

# Add season feature
stints_2023["Season"] = 2023
stints_2024["Season"] = 2024

# Combine seasons
combined_stints = pd.concat(
    [stints_2023, stints_2024],
    ignore_index=True
)

# Feature engineering
model_df = combined_stints.copy()

model_df["GP_Stint"] = (
    model_df["GP"]
    + "_S"
    + model_df["Stint"].astype(str)
)

model_df["Compound_Stint"] = (
    model_df["Compound"]
    + "_S"
    + model_df["Stint"].astype(str)
)

# Dry-only benchmark
wet_races = [
    "São Paulo Grand Prix",
    "British Grand Prix",
    "Dutch Grand Prix",
    "Canadian Grand Prix",
    "Monaco Grand Prix"
]

dry_df = model_df[
    ~model_df["GP"].isin(wet_races)
].copy()

print("Original stints:", len(model_df))
print("Dry-only stints:", len(dry_df))

# Features
X = dry_df[
    [
        "GP",
        "Compound",
        "Stint",
        "GP_Stint",
        "Compound_Stint",
        "Season",
        "AirTemp",
        "TrackTemp",
        "FreshTyre",
        "RaceProgress"
    ]
]

y = dry_df["StintLength"]

# Feature groups
categorical_features = [
    "GP",
    "Compound",
    "Stint",
    "GP_Stint",
    "Compound_Stint"
]

numerical_features = [
    "Season",
    "AirTemp",
    "TrackTemp",
    "FreshTyre",
    "RaceProgress"
]

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numerical_features
        )
    ]
)

# Model
model = Pipeline([
    ("preprocess", preprocessor),
    ("regressor", (
    XGBRegressor(
        n_estimators=100,
        max_depth=4,
        learning_rate=0.1,
        random_state=42
    )
))
])

# Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train
model.fit(X_train, y_train)

# Predict
preds = model.predict(X_test)

train_preds = model.predict(X_train)

train_mae = mean_absolute_error(
    y_train,
    train_preds
)

test_mae = mean_absolute_error(
    y_test,
    preds
)

print("Train MAE:", train_mae)
print("Test MAE:", test_mae)

# Evaluate
mae = mean_absolute_error(
    y_test,
    preds
)

print("Dry-Only + RaceProgress + FreshTyre MAE:", mae)
print("Total stints:", len(dry_df))

Original stints: 2427
Dry-only stints: 1872
Train MAE: 3.823272943496704
Test MAE: 4.403841972351074
Dry-Only + RaceProgress + FreshTyre MAE: 4.403841972351074
Total stints: 1872

In [1]:
import pandas as pd

# Load driver dataset
driver_df = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/raw_driver_2024.csv"
)

# Convert to string
driver_df["TrackStatus"] = (
    driver_df["TrackStatus"]
    .astype(str)
)

# -----------------------------------
# Create Lap-Level Flag Features
# -----------------------------------

driver_df["YellowFlag"] = (
    driver_df["TrackStatus"]
    .str.contains("2")
    .astype(int)
)

driver_df["SCFlag"] = (
    driver_df["TrackStatus"]
    .str.contains("4")
    .astype(int)
)

driver_df["RedFlag"] = (
    driver_df["TrackStatus"]
    .str.contains("5")
    .astype(int)
)

driver_df["VSCFlag"] = (
    (
        driver_df["TrackStatus"].str.contains("6")
        |
        driver_df["TrackStatus"].str.contains("7")
    )
    .astype(int)
)

# Quick sanity check

print(
    driver_df[
        [
            "TrackStatus",
            "YellowFlag",
            "SCFlag",
            "VSCFlag",
            "RedFlag"
        ]
    ].head(20)
)

print("\nTotals:\n")

print(
    driver_df[
        [
            "YellowFlag",
            "SCFlag",
            "VSCFlag",
            "RedFlag"
        ]
    ].sum()
)

   TrackStatus  YellowFlag  SCFlag  VSCFlag  RedFlag
0            1           0       0        0        0
1            1           0       0        0        0
2            1           0       0        0        0
3            1           0       0        0        0
4            1           0       0        0        0
5            1           0       0        0        0
6            1           0       0        0        0
7            1           0       0        0        0
8            1           0       0        0        0
9            1           0       0        0        0
10           1           0       0        0        0
11           1           0       0        0        0
12           1           0       0        0        0
13          12           1       0        0        0
14           1           0       0        0        0
15           1           0       0        0        0
16           1           0       0        0        0
17           1           0       0        0        0
18           1           0       0        0        0
19           1           0       0        0        0

Totals:

YellowFlag    3887
SCFlag        1030
VSCFlag        337
RedFlag        660
dtype: int64

In [ ]:
import pandas as pd

# Load driver dataset
driver_df = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/.csv"
)

# Convert to string
driver_df["TrackStatus"] = (
    driver_df["TrackStatus"]
    .astype(str)
)

# -----------------------------------
# Create Lap-Level Flag Features
# -----------------------------------

driver_df["YellowFlag"] = (
    driver_df["TrackStatus"]
    .str.contains("2")
    .astype(int)
)

driver_df["SCFlag"] = (
    driver_df["TrackStatus"]
    .str.contains("4")
    .astype(int)
)

driver_df["RedFlag"] = (
    driver_df["TrackStatus"]
    .str.contains("5")
    .astype(int)
)

driver_df["VSCFlag"] = (
    (
        driver_df["TrackStatus"].str.contains("6")
        |
        driver_df["TrackStatus"].str.contains("7")
    )
    .astype(int)
)

# Quick sanity check

print(
    driver_df[
        [
            "TrackStatus",
            "YellowFlag",
            "SCFlag",
            "VSCFlag",
            "RedFlag"
        ]
    ].head(20)
)

print("\nTotals:\n")

print(
    driver_df[
        [
            "YellowFlag",
            "SCFlag",
            "VSCFlag",
            "RedFlag"
        ]
    ].sum()
)

##### VSC/SC/Red Flag features

In [3]:
import pandas as pd

# -----------------------------------
# Track Status Feature Engineering
# -----------------------------------

def create_track_status_features(
    input_file,
    output_file
):

    # Load dataset
    df = pd.read_csv(input_file)

    # Fill missing TrackStatus
    df["TrackStatus"] = (
        df["TrackStatus"]
        .fillna("1")
        .astype(str)
    )

    # -------------------------
    # Create Lap-Level Flags
    # -------------------------

    df["YellowFlag"] = (
        df["TrackStatus"]
        .str.contains("2")
        .astype(int)
    )

    df["SCFlag"] = (
        df["TrackStatus"]
        .str.contains("4")
        .astype(int)
    )

    df["VSCFlag"] = (
        (
            df["TrackStatus"].str.contains("6")
            |
            df["TrackStatus"].str.contains("7")
        )
        .astype(int)
    )

    df["RedFlag"] = (
        df["TrackStatus"]
        .str.contains("5")
        .astype(int)
    )

    # -------------------------
    # Aggregate To Stint Level
    # -------------------------

    track_features = (
        df.groupby(
            ["GP", "Driver", "Stint"]
        )
        .agg(
            YellowLaps=("YellowFlag", "sum"),
            SCLaps=("SCFlag", "sum"),
            VSCLaps=("VSCFlag", "sum"),
            RedFlagLaps=("RedFlag", "sum")
        )
        .reset_index()
    )

    # Save
    track_features.to_csv(
        output_file,
        index=False
    )

    print(
        f"Saved: {output_file}"
    )

    print(
        "\nFeature Summary:\n"
    )

    print(
        track_features[
            [
                "YellowLaps",
                "SCLaps",
                "VSCLaps",
                "RedFlagLaps"
            ]
        ].describe()
    )

    return track_features


# -----------------------------------
# 2023
# -----------------------------------

track_features_2023 = (
    create_track_status_features(
        input_file="C:/Users/VANSH/Formula1/datasets/2023/final_merged_2023_data_with_trackstatus.csv",
        output_file="track_features_2023.csv"
    )
)

# -----------------------------------
# 2024
# -----------------------------------

track_features_2024 = (
    create_track_status_features(
        input_file="C:/Users/VANSH/Formula1/datasets/2024/raw_driver_2024.csv",
        output_file="track_features_2024.csv"
    )
)

C:\Users\VANSH\AppData\Local\Temp\ipykernel_7760\2625376450.py:13: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_file)

Saved: track_features_2023.csv

Feature Summary:

        YellowLaps       SCLaps      VSCLaps  RedFlagLaps
count  2216.000000  2216.000000  2216.000000  2216.000000
mean      0.989621     0.836643     0.298285     0.055505
std       1.884565     2.238072     0.906917     0.332018
min       0.000000     0.000000     0.000000     0.000000
25%       0.000000     0.000000     0.000000     0.000000
50%       0.000000     0.000000     0.000000     0.000000
75%       1.000000     0.000000     0.000000     0.000000
max      15.000000    21.000000     6.000000     4.000000
Saved: track_features_2024.csv

Feature Summary:

        YellowLaps       SCLaps      VSCLaps  RedFlagLaps
count  2758.000000  2758.000000  2758.000000  2758.000000
mean      1.409355     0.373459     0.122190     0.239304
std       2.089131     1.230630     0.446573     0.478807
min       0.000000     0.000000     0.000000     0.000000
25%       0.000000     0.000000     0.000000     0.000000
50%       1.000000     0.000000     0.000000     0.000000
75%       2.000000     0.000000     0.000000     0.000000
max      13.000000     9.000000     3.000000     3.000000

In [1]:
import pandas as pd

master_2023 = pd.read_csv(
    "master_stint_2023_v2.csv"
)

master_2024 = pd.read_csv(
    "master_stint_2024_v2.csv"
)

combined_df = pd.concat(
    [master_2023, master_2024],
    ignore_index=True
)

print("Original stints:", len(combined_df))

combined_df.to_csv(
    "master_stint_combined_v2.csv",
    index=False
)

Original stints: 2427

#### Retraining after TrackFeatures

In [6]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error

from xgboost import XGBRegressor
import joblib

# -----------------------------------
# Load Updated Master Datasets
# -----------------------------------

stint_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/master_stint_2023_v2.csv"
)

stint_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/master_stint_2024_v2.csv"
)

# -----------------------------------
# Add Season Feature
# -----------------------------------

stint_2023["Season"] = 2023
stint_2024["Season"] = 2024

# -----------------------------------
# Combine Seasons
# -----------------------------------

df = pd.concat(
    [stint_2023, stint_2024],
    ignore_index=True
)

print("Original stints:", len(df))

# -----------------------------------
# Dry Compounds Only
# -----------------------------------

dry_compounds = [
    "SOFT",
    "MEDIUM",
    "HARD"
]

df = df[
    df["Compound"].isin(
        dry_compounds
    )
].copy()

print("Dry-only stints:", len(df))

# -----------------------------------
# Features
# -----------------------------------

X = df[
    [
        "Compound",
        "AirTemp",
        "TrackTemp",
        "Season",
        "RaceProgress",
        "FreshTyre",
        "YellowLaps",
        "SCLaps",
        "VSCLaps",
        "RedFlagLaps",
        "GP"
    ]
]

# Target

y = df["StintLength"]

# -----------------------------------
# Feature Types
# -----------------------------------

categorical_features = [
    "Compound",
    "GP"
]

numerical_features = [
    "AirTemp",
    "TrackTemp",
    "Season",
    "RaceProgress",
    "FreshTyre",
    "YellowLaps",
    "SCLaps",
    "VSCLaps",
    "RedFlagLaps"
]

# -----------------------------------
# Preprocessing
# -----------------------------------

preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(
                handle_unknown="ignore"
            ),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numerical_features
        )
    ]
)

# -----------------------------------
# Train Test Split
# -----------------------------------

X_train, X_test, y_train, y_test = (
    train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42
    )
)

# -----------------------------------
# XGBoost Model
# -----------------------------------

model = XGBRegressor(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

pipeline = Pipeline(
    [
        ("preprocessor", preprocessor),
        ("model", model)
    ]
)

# -----------------------------------
# Train
# -----------------------------------

pipeline.fit(
    X_train,
    y_train
)

# -----------------------------------
# Predictions
# -----------------------------------

train_preds = pipeline.predict(
    X_train
)

test_preds = pipeline.predict(
    X_test
)

# -----------------------------------
# Metrics
# -----------------------------------

train_mae = mean_absolute_error(
    y_train,
    train_preds
)

test_mae = mean_absolute_error(
    y_test,
    test_preds
)

print("\nTrain MAE:", train_mae)
print("Test MAE:", test_mae)


joblib.dump(
    pipeline,
    "xgb_stint_model.pkl"
)

print(
    "Model saved successfully."
)

Original stints: 2427
Dry-only stints: 2241

Train MAE: 1.9426003694534302
Test MAE: 3.664518117904663
Model saved successfully.

In [7]:
feature_names = (
    pipeline.named_steps["preprocessor"]
    .get_feature_names_out()
)

importances = (
    pipeline.named_steps["model"]
    .feature_importances_
)

importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": importances
})

print(
    importance_df
    .sort_values(
        "Importance",
        ascending=False
    )
    .head(20)
)

                 Feature  Importance
0     cat__Compound_HARD    0.347390
6      num__RaceProgress    0.087765
8        num__YellowLaps    0.077257
9            num__SCLaps    0.073103
11      num__RedFlagLaps    0.060066
5            num__Season    0.059320
3           num__AirTemp    0.058637
2     cat__Compound_SOFT    0.055211
1   cat__Compound_MEDIUM    0.054801
4         num__TrackTemp    0.051368
10          num__VSCLaps    0.044537
7         num__FreshTyre    0.030546

In [9]:
import sys
import os
sys.path.append(os.path.abspath('..'))

from simulator.race_context import (
    get_race_context
)

from simulator.race_simulator import (
    RaceSimulator
)

context = get_race_context(
    season=2024,
    gp_name="Bahrain Grand Prix"
)

simulator = RaceSimulator()

result = simulator.simulate_strategy(
    strategy=[
        "MEDIUM",
        "HARD"
    ],
    race_context=context
)

print(result)

{'strategy': ['MEDIUM', 'HARD'], 'predicted_stints': [34.0, 14.4], 'total_laps': 48.4, 'pit_stops': 1, 'valid': False}

In [ ]:
import sys
import os
sys.path.append(os.path.abspath('..'))

from simulator.stint_predictor import StintPredictor

predictor = StintPredictor()

for compound in [
    "SOFT",
    "MEDIUM",
    "HARD"
]:

    pred = predictor.predict_stint_length(
        compound=compound,
        air_temp=22.4,
        track_temp=28.2,
        season=2024,
        race_progress=0
    )

    print(compound, pred)

SOFT 27.3
MEDIUM 34.0
HARD 31.3

In [11]:
import sys
import os
sys.path.append(os.path.abspath('..'))

from simulator.stint_predictor import (
    StintPredictor
)

predictor = StintPredictor()

print("-" * 50)
print("HARD TYRE")
print("-" * 50)

for progress in [0, 10, 20, 30, 40, 50]:

    prediction = predictor.predict_stint_length(
        compound="HARD",
        air_temp=22.4,
        track_temp=28.2,
        season=2024,
        race_progress=progress
    )

    print(
        f"RaceProgress = {progress:2d}"
        f" --> Predicted Stint = {prediction:.1f}"
    )

print("\n")

print("-" * 50)
print("MEDIUM TYRE")
print("-" * 50)

for progress in [0, 10, 20, 30, 40, 50]:

    prediction = predictor.predict_stint_length(
        compound="MEDIUM",
        air_temp=22.4,
        track_temp=28.2,
        season=2024,
        race_progress=progress
    )

    print(
        f"RaceProgress = {progress:2d}"
        f" --> Predicted Stint = {prediction:.1f}"
    )

print("\n")

print("-" * 50)
print("SOFT TYRE")
print("-" * 50)

for progress in [0, 10, 20, 30, 40, 50]:

    prediction = predictor.predict_stint_length(
        compound="SOFT",
        air_temp=22.4,
        track_temp=28.2,
        season=2024,
        race_progress=progress
    )

    print(
        f"RaceProgress = {progress:2d}"
        f" --> Predicted Stint = {prediction:.1f}"
    )

--------------------------------------------------
HARD TYRE
--------------------------------------------------
RaceProgress =  0 --> Predicted Stint = 31.3
RaceProgress = 10 --> Predicted Stint = 14.4
RaceProgress = 20 --> Predicted Stint = 14.4
RaceProgress = 30 --> Predicted Stint = 14.4
RaceProgress = 40 --> Predicted Stint = 14.4
RaceProgress = 50 --> Predicted Stint = 14.4


--------------------------------------------------
MEDIUM TYRE
--------------------------------------------------
RaceProgress =  0 --> Predicted Stint = 34.0
RaceProgress = 10 --> Predicted Stint = 7.0
RaceProgress = 20 --> Predicted Stint = 7.0
RaceProgress = 30 --> Predicted Stint = 7.0
RaceProgress = 40 --> Predicted Stint = 7.0
RaceProgress = 50 --> Predicted Stint = 7.0


--------------------------------------------------
SOFT TYRE
--------------------------------------------------
RaceProgress =  0 --> Predicted Stint = 27.3
RaceProgress = 10 --> Predicted Stint = 5.7
RaceProgress = 20 --> Predicted Stint = 5.7
RaceProgress = 30 --> Predicted Stint = 5.7
RaceProgress = 40 --> Predicted Stint = 5.7
RaceProgress = 50 --> Predicted Stint = 5.7

In [13]:
import pandas as pd
df_test = pd.read_csv(
    "C:/Users/VANSH/Formula1/notebooks/master_stint_combined_v2.csv"
)
df_test.groupby(
    "Compound"
)["RaceProgress"].describe()

,count,mean,std,min,25%,50%,75%,max
Compound,,,,,,,,
HARD,943.0,0.345114,0.215183,0.012821,0.185450,0.321429,0.523721,0.842105
INTERMEDIATE,175.0,0.439418,0.320193,0.014286,0.041667,0.492754,0.705128,0.944444
MEDIUM,914.0,0.198638,0.258697,0.012821,0.017544,0.020000,0.360000,0.977273
SOFT,384.0,0.328210,0.352113,0.012821,0.017544,0.094340,0.681818,1.000000
WET,11.0,0.474566,0.285392,0.014286,0.413043,0.420290,0.737179,0.861111

In [14]:
df_test["RaceProgress"].value_counts().sort_index()

RaceProgress
0.012821    20
0.013889    40
0.014085    68
0.014286    80
0.014493    18
            ..
0.982456     1
0.982759     1
0.985714     1
0.985915     2
1.000000     1
Name: count, Length: 509, dtype: int64

In [15]:
import sys
import os
sys.path.append(os.path.abspath('..'))

from simulator.stint_predictor import (
    StintPredictor
)

predictor = StintPredictor()

for progress in [
    0.0,
    0.25,
    0.50,
    0.75,
    1.00
]:

    pred = predictor.predict_stint_length(
        compound="HARD",
        air_temp=22.4,
        track_temp=28.2,
        season=2024,
        race_progress=progress
    )

    print(
        progress,
        pred
    )

0.0 31.3
0.25 24.3
0.5 26.5
0.75 16.9
1.0 14.4

In [ ]:
import sys
import os
sys.path.append(os.path.abspath('..'))
from simulator.race_context import (
    get_race_context
)

from simulator.race_simulator import (
    RaceSimulator
)

context = get_race_context(
    season=2024,
    gp_name="Bahrain Grand Prix"
)

simulator = RaceSimulator()

result = simulator.simulate_strategy(
    strategy=[
        "MEDIUM",
        "HARD"
    ],
    race_context=context
)

print(result)

{'strategy': ['MEDIUM', 'HARD'], 'predicted_stints': [34.0, 14.4], 'total_laps': 48.4, 'pit_stops': 1, 'valid': False}

In [17]:
import sys
import os
sys.path.append(os.path.abspath('..'))

from simulator.stint_predictor import (
    StintPredictor
)

predictor = StintPredictor()

print(
    predictor.predict_stint_length(
        compound="HARD",
        air_temp=22.4,
        track_temp=28.2,
        season=2024,
        race_progress=34/57
    )
)

23.5

In [2]:
import sys
import os
sys.path.append(os.path.abspath('..'))

from simulator.race_context import get_race_context
from simulator.race_simulator import RaceSimulator

context = get_race_context(
    season=2024,
    gp_name="Bahrain Grand Prix"
)

simulator = RaceSimulator()

result = simulator.simulate_strategy(
    strategy=[
        "MEDIUM",
        "HARD"
    ],
    race_context=context
)

print(result)

{'strategy': ['MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.596], 'predicted_stints': [34.0, 23.5], 'total_laps': 57.5, 'race_laps': 57, 'pit_stops': 1, 'valid': True}

In [ ]:
import sys
import os
sys.path.append(os.path.abspath('..'))

from simulator.race_context import get_race_context
from simulator.race_simulator import RaceSimulator
from simulator.strategy_generator import (
    generate_strategies
)

context = get_race_context(
    season=2024,
    gp_name="Bahrain Grand Prix"
)

simulator = RaceSimulator()

strategies = generate_strategies()

for strategy in strategies:

    result = simulator.simulate_strategy(
        strategy=strategy,
        race_context=context
    )

    print(result)

{'strategy': ['SOFT', 'HARD'], 'race_progresses': [0.0, 0.474], 'predicted_stints': [27.3, 25.5], 'total_laps': 52.8, 'race_laps': 57, 'pit_stops': 1, 'valid': False}
{'strategy': ['MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.596], 'predicted_stints': [34.0, 23.5], 'total_laps': 57.5, 'race_laps': 57, 'pit_stops': 1, 'valid': True}
{'strategy': ['SOFT', 'MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.474, 0.877], 'predicted_stints': [27.3, 23.1, 16.2], 'total_laps': 66.6, 'race_laps': 57, 'pit_stops': 2, 'valid': True}
{'strategy': ['MEDIUM', 'SOFT', 'HARD'], 'race_progresses': [0.0, 0.596, 0.965], 'predicted_stints': [34.0, 21.4, 14.4], 'total_laps': 69.8, 'race_laps': 57, 'pit_stops': 2, 'valid': True}
{'strategy': ['HARD', 'MEDIUM'], 'race_progresses': [0.0, 0.544], 'predicted_stints': [31.3, 23.3], 'total_laps': 54.6, 'race_laps': 57, 'pit_stops': 1, 'valid': False}

In [2]:
import sys
import os
sys.path.append(os.path.abspath('..'))

from simulator.race_context import get_race_context
from simulator.race_simulator import RaceSimulator
from simulator.strategy_generator import (
    generate_strategies
)

context = get_race_context(
    season=2024,
    gp_name="Bahrain Grand Prix"
)

simulator = RaceSimulator()

strategies = generate_strategies()

for strategy in strategies:

    result = simulator.simulate_strategy(
        strategy=strategy,
        race_context=context
    )

    print(result)

{'strategy': ['SOFT', 'HARD'], 'race_progresses': [0.0, 0.474], 'predicted_stints': [27.3, 25.5], 'total_laps': 52.8, 'race_laps': 57, 'coverage_margin': -4.2, 'pit_stops': 1, 'valid': False}
{'strategy': ['MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.596], 'predicted_stints': [34.0, 23.5], 'total_laps': 57.5, 'race_laps': 57, 'coverage_margin': 0.5, 'pit_stops': 1, 'valid': True}
{'strategy': ['SOFT', 'MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.474, 0.877], 'predicted_stints': [27.3, 23.1, 16.2], 'total_laps': 66.6, 'race_laps': 57, 'coverage_margin': 9.6, 'pit_stops': 2, 'valid': True}
{'strategy': ['MEDIUM', 'SOFT', 'HARD'], 'race_progresses': [0.0, 0.596, 0.965], 'predicted_stints': [34.0, 21.4, 14.4], 'total_laps': 69.8, 'race_laps': 57, 'coverage_margin': 12.8, 'pit_stops': 2, 'valid': True}
{'strategy': ['HARD', 'MEDIUM'], 'race_progresses': [0.0, 0.544], 'predicted_stints': [31.3, 23.3], 'total_laps': 54.6, 'race_laps': 57, 'coverage_margin': -2.4, 'pit_stops': 1, 'valid': False}

In [17]:
import sys
import os
sys.path.append(os.path.abspath('..'))

from simulator.race_context import get_race_context
from simulator.race_simulator import RaceSimulator
from simulator.strategy_generator import (
    generate_strategies
)

context = get_race_context(
    season=2024,
    gp_name="Bahrain Grand Prix"
)

simulator = RaceSimulator()

strategies = generate_strategies()

for strategy in strategies:

    result = simulator.simulate_strategy(
        strategy=strategy,
        race_context=context
    )

    print(result)

ValueError: columns are missing: {'GP'}

In [1]:
import sys
import os
sys.path.append(os.path.abspath('..'))

from simulator.race_context import get_race_context
from simulator.race_simulator import RaceSimulator
from simulator.strategy_generator import (
    generate_strategies
)

context = get_race_context(
    season=2024,
    gp_name="Bahrain Grand Prix"
)

simulator = RaceSimulator()

strategies = generate_strategies()

for strategy in strategies:

    result = simulator.simulate_strategy(
        strategy=strategy,
        race_context=context
    )

    print(result)

{'strategy': ['SOFT', 'HARD'], 'race_progresses': [0.0, 0.193], 'predicted_stints': [10.7, 17.3], 'total_laps': 28.0, 'race_laps': 57, 'coverage_margin': -29.0, 'pit_stops': 1, 'valid': False}
{'strategy': ['MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.246], 'predicted_stints': [13.8, 17.9], 'total_laps': 31.7, 'race_laps': 57, 'coverage_margin': -25.3, 'pit_stops': 1, 'valid': False}
{'strategy': ['HARD', 'MEDIUM'], 'race_progresses': [0.0, 0.246], 'predicted_stints': [14.5, 16.7], 'total_laps': 31.2, 'race_laps': 57, 'coverage_margin': -25.8, 'pit_stops': 1, 'valid': False}
{'strategy': ['SOFT', 'HARD', 'HARD'], 'race_progresses': [0.0, 0.193, 0.491], 'predicted_stints': [10.7, 17.3, 18.4], 'total_laps': 46.4, 'race_laps': 57, 'coverage_margin': -10.6, 'pit_stops': 2, 'valid': False}
{'strategy': ['MEDIUM', 'HARD', 'HARD'], 'race_progresses': [0.0, 0.246, 0.561], 'predicted_stints': [13.8, 17.9, 17.4], 'total_laps': 49.1, 'race_laps': 57, 'coverage_margin': -7.9, 'pit_stops': 2, 'valid': False}
{'strategy': ['SOFT', 'SOFT', 'HARD'], 'race_progresses': [0.0, 0.193, 0.474], 'predicted_stints': [10.7, 15.7, 17.4], 'total_laps': 43.8, 'race_laps': 57, 'coverage_margin': -13.2, 'pit_stops': 2, 'valid': False}
{'strategy': ['MEDIUM', 'MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.246, 0.544], 'predicted_stints': [13.8, 16.7, 19.0], 'total_laps': 49.5, 'race_laps': 57, 'coverage_margin': -7.5, 'pit_stops': 2, 'valid': False}
{'strategy': ['SOFT', 'HARD', 'SOFT'], 'race_progresses': [0.0, 0.193, 0.491], 'predicted_stints': [10.7, 17.3, 17.1], 'total_laps': 45.1, 'race_laps': 57, 'coverage_margin': -11.9, 'pit_stops': 2, 'valid': False}
{'strategy': ['MEDIUM', 'HARD', 'SOFT'], 'race_progresses': [0.0, 0.246, 0.561], 'predicted_stints': [13.8, 17.9, 16.7], 'total_laps': 48.4, 'race_laps': 57, 'coverage_margin': -8.6, 'pit_stops': 2, 'valid': False}
{'strategy': ['SOFT', 'MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.193, 0.474], 'predicted_stints': [10.7, 16.1, 17.4], 'total_laps': 44.2, 'race_laps': 57, 'coverage_margin': -12.8, 'pit_stops': 2, 'valid': False}
{'strategy': ['MEDIUM', 'SOFT', 'HARD'], 'race_progresses': [0.0, 0.246, 0.526], 'predicted_stints': [13.8, 16.0, 18.7], 'total_laps': 48.5, 'race_laps': 57, 'coverage_margin': -8.5, 'pit_stops': 2, 'valid': False}

In [1]:
import sys
import os
sys.path.append(os.path.abspath('..'))

from simulator.race_context import get_race_context
from simulator.race_simulator import RaceSimulator
from simulator.strategy_generator import (
    generate_strategies
)

context = get_race_context(
    season=2024,
    gp_name="Bahrain Grand Prix"
)

simulator = RaceSimulator()

strategies = generate_strategies()

for strategy in strategies:

    result = simulator.simulate_strategy(
        strategy=strategy,
        race_context=context
    )

    print(result)

{'strategy': ['SOFT', 'HARD'], 'race_progresses': [0.0, 0.193], 'predicted_stints': [10.7, 17.3], 'total_laps': 28.0, 'race_laps': 57, 'coverage_margin': -29.0, 'pit_stops': 1, 'valid': False, 'circuit_type': 'Permanent'}
{'strategy': ['MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.246], 'predicted_stints': [13.8, 17.9], 'total_laps': 31.7, 'race_laps': 57, 'coverage_margin': -25.3, 'pit_stops': 1, 'valid': False, 'circuit_type': 'Permanent'}
{'strategy': ['HARD', 'MEDIUM'], 'race_progresses': [0.0, 0.246], 'predicted_stints': [14.5, 16.7], 'total_laps': 31.2, 'race_laps': 57, 'coverage_margin': -25.8, 'pit_stops': 1, 'valid': False, 'circuit_type': 'Permanent'}
{'strategy': ['SOFT', 'HARD', 'HARD'], 'race_progresses': [0.0, 0.193, 0.491], 'predicted_stints': [10.7, 17.3, 18.4], 'total_laps': 46.4, 'race_laps': 57, 'coverage_margin': -10.6, 'pit_stops': 2, 'valid': False, 'circuit_type': 'Permanent'}
{'strategy': ['MEDIUM', 'HARD', 'HARD'], 'race_progresses': [0.0, 0.246, 0.561], 'predicted_stints': [13.8, 17.9, 17.4], 'total_laps': 49.1, 'race_laps': 57, 'coverage_margin': -7.9, 'pit_stops': 2, 'valid': False, 'circuit_type': 'Permanent'}
{'strategy': ['SOFT', 'SOFT', 'HARD'], 'race_progresses': [0.0, 0.193, 0.474], 'predicted_stints': [10.7, 15.7, 17.4], 'total_laps': 43.8, 'race_laps': 57, 'coverage_margin': -13.2, 'pit_stops': 2, 'valid': False, 'circuit_type': 'Permanent'}
{'strategy': ['MEDIUM', 'MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.246, 0.544], 'predicted_stints': [13.8, 16.7, 19.0], 'total_laps': 49.5, 'race_laps': 57, 'coverage_margin': -7.5, 'pit_stops': 2, 'valid': False, 'circuit_type': 'Permanent'}
{'strategy': ['SOFT', 'HARD', 'SOFT'], 'race_progresses': [0.0, 0.193, 0.491], 'predicted_stints': [10.7, 17.3, 17.1], 'total_laps': 45.1, 'race_laps': 57, 'coverage_margin': -11.9, 'pit_stops': 2, 'valid': False, 'circuit_type': 'Permanent'}
{'strategy': ['MEDIUM', 'HARD', 'SOFT'], 'race_progresses': [0.0, 0.246, 0.561], 'predicted_stints': [13.8, 17.9, 16.7], 'total_laps': 48.4, 'race_laps': 57, 'coverage_margin': -8.6, 'pit_stops': 2, 'valid': False, 'circuit_type': 'Permanent'}
{'strategy': ['SOFT', 'MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.193, 0.474], 'predicted_stints': [10.7, 16.1, 17.4], 'total_laps': 44.2, 'race_laps': 57, 'coverage_margin': -12.8, 'pit_stops': 2, 'valid': False, 'circuit_type': 'Permanent'}
{'strategy': ['MEDIUM', 'SOFT', 'HARD'], 'race_progresses': [0.0, 0.246, 0.526], 'predicted_stints': [13.8, 16.0, 18.7], 'total_laps': 48.5, 'race_laps': 57, 'coverage_margin': -8.5, 'pit_stops': 2, 'valid': False, 'circuit_type': 'Permanent'}

In [10]:
import sys
import os
sys.path.append(os.path.abspath('..'))

from simulator.race_context import get_race_context
from simulator.race_simulator import RaceSimulator
from simulator.strategy_generator import (
    generate_strategies
)

context = get_race_context(
    season=2023,
    gp_name="British Grand Prix"
)

simulator = RaceSimulator()

strategies = generate_strategies()

for strategy in strategies:

    result = simulator.simulate_strategy(
        strategy=strategy,
        race_context=context
    )

    print(result)

{'strategy': ['SOFT', 'HARD'], 'race_progresses': [0.0, 0.308], 'predicted_stints': [15.6, 19.1], 'total_laps': 34.7, 'race_laps': 52, 'coverage_margin': -17.3, 'pit_stops': 1, 'valid': False}
{'strategy': ['MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.404], 'predicted_stints': [21.0, 20.2], 'total_laps': 41.2, 'race_laps': 52, 'coverage_margin': -10.8, 'pit_stops': 1, 'valid': False}
{'strategy': ['HARD', 'MEDIUM'], 'race_progresses': [0.0, 0.365], 'predicted_stints': [18.9, 16.0], 'total_laps': 34.9, 'race_laps': 52, 'coverage_margin': -17.1, 'pit_stops': 1, 'valid': False}
{'strategy': ['SOFT', 'HARD', 'HARD'], 'race_progresses': [0.0, 0.308, 0.673], 'predicted_stints': [15.6, 19.1, 15.8], 'total_laps': 50.5, 'race_laps': 52, 'coverage_margin': -1.5, 'pit_stops': 2, 'valid': False}
{'strategy': ['MEDIUM', 'HARD', 'HARD'], 'race_progresses': [0.0, 0.404, 0.788], 'predicted_stints': [21.0, 20.2, 14.7], 'total_laps': 55.9, 'race_laps': 52, 'coverage_margin': 3.9, 'pit_stops': 2, 'valid': True}
{'strategy': ['SOFT', 'SOFT', 'HARD'], 'race_progresses': [0.0, 0.308, 0.596], 'predicted_stints': [15.6, 15.4, 19.3], 'total_laps': 50.3, 'race_laps': 52, 'coverage_margin': -1.7, 'pit_stops': 2, 'valid': False}
{'strategy': ['MEDIUM', 'MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.404, 0.731], 'predicted_stints': [21.0, 16.9, 16.2], 'total_laps': 54.1, 'race_laps': 52, 'coverage_margin': 2.1, 'pit_stops': 2, 'valid': True}
{'strategy': ['SOFT', 'HARD', 'SOFT'], 'race_progresses': [0.0, 0.308, 0.673], 'predicted_stints': [15.6, 19.1, 14.4], 'total_laps': 49.1, 'race_laps': 52, 'coverage_margin': -2.9, 'pit_stops': 2, 'valid': False}
{'strategy': ['MEDIUM', 'HARD', 'SOFT'], 'race_progresses': [0.0, 0.404, 0.788], 'predicted_stints': [21.0, 20.2, 12.0], 'total_laps': 53.2, 'race_laps': 52, 'coverage_margin': 1.2, 'pit_stops': 2, 'valid': True}
{'strategy': ['SOFT', 'MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.308, 0.615], 'predicted_stints': [15.6, 16.2, 18.9], 'total_laps': 50.7, 'race_laps': 52, 'coverage_margin': -1.3, 'pit_stops': 2, 'valid': False}
{'strategy': ['MEDIUM', 'SOFT', 'HARD'], 'race_progresses': [0.0, 0.404, 0.712], 'predicted_stints': [21.0, 16.0, 16.4], 'total_laps': 53.4, 'race_laps': 52, 'coverage_margin': 1.4, 'pit_stops': 2, 'valid': True}

In [12]:
import sys
import os
sys.path.append(os.path.abspath('..'))

from simulator.race_context import get_race_context
from simulator.race_simulator import RaceSimulator
from simulator.strategy_generator import (
    generate_strategies
)

context = get_race_context(
    season=2023,
    gp_name="Australian Grand Prix"
)

simulator = RaceSimulator()

strategies = generate_strategies()

for strategy in strategies:

    result = simulator.simulate_strategy(
        strategy=strategy,
        race_context=context
    )

    print(result)

{'strategy': ['SOFT', 'HARD'], 'race_progresses': [0.0, 0.034], 'predicted_stints': [1.7, 13.6], 'total_laps': 15.3, 'race_laps': 58, 'coverage_margin': -42.7, 'pit_stops': 1, 'valid': False}
{'strategy': ['MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.121], 'predicted_stints': [6.9, 16.1], 'total_laps': 23.0, 'race_laps': 58, 'coverage_margin': -35.0, 'pit_stops': 1, 'valid': False}
{'strategy': ['HARD', 'MEDIUM'], 'race_progresses': [0.0, 0.259], 'predicted_stints': [14.9, 14.4], 'total_laps': 29.3, 'race_laps': 58, 'coverage_margin': -28.7, 'pit_stops': 1, 'valid': False}
{'strategy': ['SOFT', 'HARD', 'HARD'], 'race_progresses': [0.0, 0.034, 0.276], 'predicted_stints': [1.7, 13.6, 20.9], 'total_laps': 36.2, 'race_laps': 58, 'coverage_margin': -21.8, 'pit_stops': 2, 'valid': False}
{'strategy': ['MEDIUM', 'HARD', 'HARD'], 'race_progresses': [0.0, 0.121, 0.397], 'predicted_stints': [6.9, 16.1, 22.2], 'total_laps': 45.2, 'race_laps': 58, 'coverage_margin': -12.8, 'pit_stops': 2, 'valid': False}
{'strategy': ['SOFT', 'SOFT', 'HARD'], 'race_progresses': [0.0, 0.034, 0.103], 'predicted_stints': [1.7, 3.7, 16.9], 'total_laps': 22.3, 'race_laps': 58, 'coverage_margin': -35.7, 'pit_stops': 2, 'valid': False}
{'strategy': ['MEDIUM', 'MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.121, 0.31], 'predicted_stints': [6.9, 11.1, 21.0], 'total_laps': 39.0, 'race_laps': 58, 'coverage_margin': -19.0, 'pit_stops': 2, 'valid': False}
{'strategy': ['SOFT', 'HARD', 'SOFT'], 'race_progresses': [0.0, 0.034, 0.276], 'predicted_stints': [1.7, 13.6, 14.1], 'total_laps': 29.4, 'race_laps': 58, 'coverage_margin': -28.6, 'pit_stops': 2, 'valid': False}
{'strategy': ['MEDIUM', 'HARD', 'SOFT'], 'race_progresses': [0.0, 0.121, 0.397], 'predicted_stints': [6.9, 16.1, 15.3], 'total_laps': 38.3, 'race_laps': 58, 'coverage_margin': -19.7, 'pit_stops': 2, 'valid': False}
{'strategy': ['SOFT', 'MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.034, 0.121], 'predicted_stints': [1.7, 5.3, 16.1], 'total_laps': 23.1, 'race_laps': 58, 'coverage_margin': -34.9, 'pit_stops': 2, 'valid': False}
{'strategy': ['MEDIUM', 'SOFT', 'HARD'], 'race_progresses': [0.0, 0.121, 0.293], 'predicted_stints': [6.9, 9.6, 21.0], 'total_laps': 37.5, 'race_laps': 58, 'coverage_margin': -20.5, 'pit_stops': 2, 'valid': False}

In [7]:
import pandas as pd
df = pd.read_csv(
    "C:/Users/VANSH/Formula1/notebooks/master_stint_combined_v2.csv")
df['GP'].unique()

array(['Australian Grand Prix', 'Austrian Grand Prix',
       'Azerbaijan Grand Prix', 'Bahrain Grand Prix',
       'Belgian Grand Prix', 'British Grand Prix', 'Canadian Grand Prix',
       'Dutch Grand Prix', 'Hungarian Grand Prix', 'Italian Grand Prix',
       'Japanese Grand Prix', 'Las Vegas Grand Prix',
       'Mexico City Grand Prix', 'Miami Grand Prix', 'Monaco Grand Prix',
       'Qatar Grand Prix', 'Saudi Arabian Grand Prix',
       'Singapore Grand Prix', 'Spanish Grand Prix',
       'São Paulo Grand Prix', 'United States Grand Prix',
       'Abu Dhabi Grand Prix', 'Chinese Grand Prix',
       'Emilia Romagna Grand Prix'], dtype=object)

##### TrackIntelligence

In [3]:
import pandas as pd

# -----------------------------------
# Load Master Stint Dataset
# -----------------------------------

master = pd.read_csv(
    "master_stint_combined_v2.csv",
)

# -----------------------------------
# Load Circuit Metadata
# -----------------------------------

metadata = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/circuit_metadata.csv",
    encoding="cp1252",
)

# Remove any previously merged circuit metadata so reruns stay stable
metadata_cols = [
    "CircuitType",
    "TrackLength",
    "TrackAbrasiveness",
]
master = master.drop(
    columns=[col for col in metadata_cols if col in master.columns],
    errors="ignore",
)

# -----------------------------------
# Merge on GP
# -----------------------------------

master = master.merge(
    metadata,
    on="GP",
    how="left"
)

# -----------------------------------
# Diagnostics
# -----------------------------------

print("Master Shape :", master.shape)
print("Metadata Shape :", metadata.shape)



# -----------------------------------
# Save Updated Dataset
# -----------------------------------

master.to_csv(
    "master_stint_combined_v2.csv",
    index=False,
)

print("\nSaved: master_stint_combined_v2.csv")

Master Shape : (2427, 20)
Metadata Shape : (24, 4)

Saved: master_stint_combined_v2.csv

In [7]:
master.columns

Index(['GP', 'Driver', 'Stint', 'Compound', 'StintLength', 'AirTemp',
       'TrackTemp', 'FreshTyre', 'RaceProgress', 'YellowLaps', 'SCLaps',
       'VSCLaps', 'RedFlagLaps', 'CircuitType_x', 'TrackLength_x',
       'CircuitType_y', 'TrackLength_y', 'CircuitType', 'TrackLength'],
      dtype='object')

In [8]:
stint_2023 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2023/master_stint_2023_v2.csv")
stint_2023.columns

Index(['GP', 'Driver', 'Stint', 'Compound', 'StintLength', 'AirTemp',
       'TrackTemp', 'FreshTyre', 'RaceProgress', 'YellowLaps', 'SCLaps',
       'VSCLaps', 'RedFlagLaps'],
      dtype='object')

In [3]:
import pandas as pd

metadata = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/circuit_metadata.csv",
    encoding="cp1252"
)

for season in [2023, 2024]:

    master = pd.read_csv(
        f"master_stint_{season}_v3.csv"
)

    # Remove any previously merged circuit metadata so reruns stay stable
    metadata_cols = [
        "CircuitType",
        "TrackLength",
        "TrackAbrasiveness",
        "AverageCornerSpeed"
]
    master = master.drop(
        columns=[col for col in metadata_cols if col in master.columns],
        errors="ignore",
    )

    master = master.merge(
        metadata,
        on="GP",
        how="left"
)

    print(f"\n{season}")
    print(
        master[
            [
                "CircuitType",
                "TrackLength",
                "TrackAbrasiveness",
                "AverageCornerSpeed"
            ]
        ].isna().sum()
    )

    master.to_csv(
        f"master_stint_{season}_v3.csv",
        index=False
    )

    print(
        f"Saved: master_stint_{season}_v3.csv"
    )

2023
CircuitType           49
TrackLength           49
TrackAbrasiveness     49
AverageCornerSpeed    49
dtype: int64
Saved: master_stint_2023_v3.csv

2024
CircuitType           50
TrackLength           50
TrackAbrasiveness     50
AverageCornerSpeed    50
dtype: int64
Saved: master_stint_2024_v3.csv

In [4]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error

from xgboost import XGBRegressor
import joblib

# -----------------------------------
# Load Updated Master Datasets
# -----------------------------------

stint_2023 = pd.read_csv(
    "master_stint_2023_v3.csv"
)

stint_2024 = pd.read_csv(
    "master_stint_2024_v3.csv"
)

# -----------------------------------
# Add Season Feature
# -----------------------------------

stint_2023["Season"] = 2023
stint_2024["Season"] = 2024

# -----------------------------------
# Combine Seasons
# -----------------------------------

df = pd.concat(
    [stint_2023, stint_2024],
    ignore_index=True
)

print("Original stints:", len(df))

# -----------------------------------
# Dry Compounds Only
# -----------------------------------

dry_compounds = [
    "SOFT",
    "MEDIUM",
    "HARD"
]

df = df[
    df["Compound"].isin(
        dry_compounds
    )
].copy()

print("Dry-only stints:", len(df))

# -----------------------------------
# Features
# -----------------------------------

X = df[
    [
        "Compound",
        "AirTemp",
        "TrackTemp",
        "Season",
        "RaceProgress",
        "FreshTyre",
        "YellowLaps",
        "SCLaps",
        "VSCLaps",
        "RedFlagLaps",
        "GP",
        "CircuitType",
        "TrackLength",
        "TrackAbrasiveness",
        "AverageCornerSpeed"
    ]
]

# Target

y = df["StintLength"]

# -----------------------------------
# Feature Types
# -----------------------------------

categorical_features = [
    "Compound",
    "GP",
    "CircuitType",
    "TrackAbrasiveness"
]

numerical_features = [
    "AirTemp",
    "TrackTemp",
    "TrackLength",
    "Season",
    "RaceProgress",
    "FreshTyre",
    "YellowLaps",
    "SCLaps",
    "VSCLaps",
    "RedFlagLaps",
    "AverageCornerSpeed"
]

# -----------------------------------
# Preprocessing
# -----------------------------------

preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(
                handle_unknown="ignore"
            ),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numerical_features
        )
    ]
)

# -----------------------------------
# Train Test Split
# -----------------------------------

X_train, X_test, y_train, y_test = (
    train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42
    )
)

# -----------------------------------
# XGBoost Model
# -----------------------------------

model = XGBRegressor(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

pipeline = Pipeline(
    [
        ("preprocessor", preprocessor),
        ("model", model)
    ]
)

# -----------------------------------
# Train
# -----------------------------------

pipeline.fit(
    X_train,
    y_train
)

# -----------------------------------
# Predictions
# -----------------------------------

train_preds = pipeline.predict(
    X_train
)

test_preds = pipeline.predict(
    X_test
)

# -----------------------------------
# Metrics
# -----------------------------------

train_mae = mean_absolute_error(
    y_train,
    train_preds
)

test_mae = mean_absolute_error(
    y_test,
    test_preds
)

print("\nTrain MAE:", train_mae)
print("Test MAE:", test_mae)


joblib.dump(
    pipeline,
    "xgb_stint_model.pkl"
)

print(
    "Model saved successfully."
)

Original stints: 2427
Dry-only stints: 2241

Train MAE: 1.7719210386276245
Test MAE: 3.5917935371398926
Model saved successfully.

In [7]:
feature_names = (
    pipeline.named_steps["preprocessor"]
    .get_feature_names_out()
)

importances = (
    pipeline.named_steps["model"]
    .feature_importances_
)

importance_df = pd.DataFrame(
    {
        "Feature": feature_names,
        "Importance": importances
    }
).sort_values(
    "Importance",
    ascending=False
)

print(
    importance_df.head(20)
)

                              Feature  Importance
32         cat__TrackAbrasiveness_Low    0.087636
20          cat__GP_Monaco Grand Prix    0.068711
39                   num__TrackLength    0.068036
27         cat__CircuitType_Permanent    0.058701
0                  cat__Compound_HARD    0.056238
9          cat__GP_British Grand Prix    0.045292
33      cat__TrackAbrasiveness_Medium    0.040027
4       cat__GP_Australian Grand Prix    0.035262
47            num__AverageCornerSpeed    0.033902
13  cat__GP_Emilia Romagna Grand Prix    0.031982
28     cat__CircuitType_SemiPermanent    0.026453
21           cat__GP_Qatar Grand Prix    0.025992
7          cat__GP_Bahrain Grand Prix    0.025411
35     cat__TrackAbrasiveness_VeryLow    0.023703
44                        num__SCLaps    0.022491
29            cat__CircuitType_Street    0.022451
34    cat__TrackAbrasiveness_VeryHigh    0.021246
40                        num__Season    0.020905
41                  num__RaceProgress    0.019301
1                cat__Compound_MEDIUM    0.019070

In [8]:
from sklearn.model_selection import (
    KFold,
    cross_val_score
)

cv = KFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scores = cross_val_score(
    pipeline,
    X,
    y,
    cv=cv,
    scoring="neg_mean_absolute_error",
    n_jobs=-1
)

mae_scores = -scores

print("\nFold MAEs:")
print(mae_scores)

print(
    "\nMean MAE:",
    mae_scores.mean()
)

print(
    "Std MAE:",
    mae_scores.std()
)

Fold MAEs:
[3.59825039 3.74857402 3.84332824 3.7362361  3.69270897]

Mean MAE: 3.723819541931152
Std MAE: 0.07973049995867146

In [1]:
import sys
import os
sys.path.append(os.path.abspath('..'))

from simulator.race_context import get_race_context
from simulator.race_simulator import RaceSimulator
from simulator.strategy_generator import (
    generate_strategies
)

context = get_race_context(
    season=2023,
    gp_name="Australian Grand Prix"
)

simulator = RaceSimulator()

strategies = generate_strategies()

for strategy in strategies:

    result = simulator.simulate_strategy(
        strategy=strategy,
        race_context=context
    )

    print(result)

{'strategy': ['SOFT', 'HARD'], 'race_progresses': [0.0, 0.034], 'predicted_stints': [2.5, 56], 'total_laps': 58.5, 'race_laps': 58, 'coverage_margin': 0.5, 'pit_stops': 1, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'SemiPermanent'}
{'strategy': ['MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.103], 'predicted_stints': [6.2, 52], 'total_laps': 58.2, 'race_laps': 58, 'coverage_margin': 0.2, 'pit_stops': 1, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'SemiPermanent'}
{'strategy': ['HARD', 'MEDIUM'], 'race_progresses': [0.0, 0.276], 'predicted_stints': [16.4, 42], 'total_laps': 58.4, 'race_laps': 58, 'coverage_margin': 0.4, 'pit_stops': 1, 'valid': True, 'final_compound': 'MEDIUM', 'circuit_type': 'SemiPermanent'}
{'strategy': ['SOFT', 'HARD', 'HARD'], 'race_progresses': [0.0, 0.034, 0.276], 'predicted_stints': [2.5, 14.5, 42], 'total_laps': 59.0, 'race_laps': 58, 'coverage_margin': 1.0, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'SemiPermanent'}
{'strategy': ['MEDIUM', 'HARD', 'HARD'], 'race_progresses': [0.0, 0.103, 0.431], 'predicted_stints': [6.2, 19.4, 33], 'total_laps': 58.6, 'race_laps': 58, 'coverage_margin': 0.6, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'SemiPermanent'}
{'strategy': ['SOFT', 'SOFT', 'HARD'], 'race_progresses': [0.0, 0.034, 0.103], 'predicted_stints': [2.5, 4.0, 52], 'total_laps': 58.5, 'race_laps': 58, 'coverage_margin': 0.5, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'SemiPermanent'}
{'strategy': ['MEDIUM', 'MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.103, 0.31], 'predicted_stints': [6.2, 12.2, 40], 'total_laps': 58.4, 'race_laps': 58, 'coverage_margin': 0.4, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'SemiPermanent'}
{'strategy': ['SOFT', 'HARD', 'SOFT'], 'race_progresses': [0.0, 0.034, 0.276], 'predicted_stints': [2.5, 14.5, 42], 'total_laps': 59.0, 'race_laps': 58, 'coverage_margin': 1.0, 'pit_stops': 2, 'valid': True, 'final_compound': 'SOFT', 'circuit_type': 'SemiPermanent'}
{'strategy': ['MEDIUM', 'HARD', 'SOFT'], 'race_progresses': [0.0, 0.103, 0.431], 'predicted_stints': [6.2, 19.4, 33], 'total_laps': 58.6, 'race_laps': 58, 'coverage_margin': 0.6, 'pit_stops': 2, 'valid': True, 'final_compound': 'SOFT', 'circuit_type': 'SemiPermanent'}
{'strategy': ['SOFT', 'MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.034, 0.121], 'predicted_stints': [2.5, 4.8, 51], 'total_laps': 58.3, 'race_laps': 58, 'coverage_margin': 0.3, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'SemiPermanent'}
{'strategy': ['MEDIUM', 'SOFT', 'HARD'], 'race_progresses': [0.0, 0.103, 0.31], 'predicted_stints': [6.2, 11.6, 40], 'total_laps': 57.8, 'race_laps': 58, 'coverage_margin': -0.2, 'pit_stops': 2, 'valid': False, 'final_compound': 'HARD', 'circuit_type': 'SemiPermanent'}

In [2]:
import sys
import os
sys.path.append(os.path.abspath('..'))

from simulator.race_context import get_race_context
from simulator.race_simulator import RaceSimulator
from simulator.strategy_generator import (
    generate_strategies
)

context = get_race_context(
    season=2023,
    gp_name="Bahrain Grand Prix"
)

simulator = RaceSimulator()

strategies = generate_strategies()

for strategy in strategies:

    result = simulator.simulate_strategy(
        strategy=strategy,
        race_context=context
    )

    print(result)

{'strategy': ['SOFT', 'HARD'], 'race_progresses': [0.0, 0.14], 'predicted_stints': [7.9, 49], 'total_laps': 56.9, 'race_laps': 57, 'coverage_margin': -0.1, 'pit_stops': 1, 'valid': False, 'final_compound': 'HARD', 'circuit_type': 'Permanent'}
{'strategy': ['MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.211], 'predicted_stints': [11.5, 45], 'total_laps': 56.5, 'race_laps': 57, 'coverage_margin': -0.5, 'pit_stops': 1, 'valid': False, 'final_compound': 'HARD', 'circuit_type': 'Permanent'}
{'strategy': ['HARD', 'MEDIUM'], 'race_progresses': [0.0, 0.228], 'predicted_stints': [13.0, 44], 'total_laps': 57.0, 'race_laps': 57, 'coverage_margin': 0.0, 'pit_stops': 1, 'valid': True, 'final_compound': 'MEDIUM', 'circuit_type': 'Permanent'}
{'strategy': ['SOFT', 'HARD', 'HARD'], 'race_progresses': [0.0, 0.14, 0.386], 'predicted_stints': [7.9, 14.4, 35], 'total_laps': 57.3, 'race_laps': 57, 'coverage_margin': 0.3, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent'}
{'strategy': ['MEDIUM', 'HARD', 'HARD'], 'race_progresses': [0.0, 0.211, 0.509], 'predicted_stints': [11.5, 17.1, 28], 'total_laps': 56.6, 'race_laps': 57, 'coverage_margin': -0.4, 'pit_stops': 2, 'valid': False, 'final_compound': 'HARD', 'circuit_type': 'Permanent'}
{'strategy': ['SOFT', 'SOFT', 'HARD'], 'race_progresses': [0.0, 0.14, 0.351], 'predicted_stints': [7.9, 12.5, 37], 'total_laps': 57.4, 'race_laps': 57, 'coverage_margin': 0.4, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent'}
{'strategy': ['MEDIUM', 'MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.211, 0.491], 'predicted_stints': [11.5, 15.8, 29], 'total_laps': 56.3, 'race_laps': 57, 'coverage_margin': -0.7, 'pit_stops': 2, 'valid': False, 'final_compound': 'HARD', 'circuit_type': 'Permanent'}
{'strategy': ['SOFT', 'HARD', 'SOFT'], 'race_progresses': [0.0, 0.14, 0.386], 'predicted_stints': [7.9, 14.4, 35], 'total_laps': 57.3, 'race_laps': 57, 'coverage_margin': 0.3, 'pit_stops': 2, 'valid': True, 'final_compound': 'SOFT', 'circuit_type': 'Permanent'}
{'strategy': ['MEDIUM', 'HARD', 'SOFT'], 'race_progresses': [0.0, 0.211, 0.509], 'predicted_stints': [11.5, 17.1, 28], 'total_laps': 56.6, 'race_laps': 57, 'coverage_margin': -0.4, 'pit_stops': 2, 'valid': False, 'final_compound': 'SOFT', 'circuit_type': 'Permanent'}
{'strategy': ['SOFT', 'MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.14, 0.386], 'predicted_stints': [7.9, 14.2, 35], 'total_laps': 57.1, 'race_laps': 57, 'coverage_margin': 0.1, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent'}
{'strategy': ['MEDIUM', 'SOFT', 'HARD'], 'race_progresses': [0.0, 0.211, 0.474], 'predicted_stints': [11.5, 15.1, 30], 'total_laps': 56.6, 'race_laps': 57, 'coverage_margin': -0.4, 'pit_stops': 2, 'valid': False, 'final_compound': 'HARD', 'circuit_type': 'Permanent'}

In [3]:
import sys
import os
sys.path.append(os.path.abspath('..'))

from simulator.race_context import get_race_context
from simulator.race_simulator import RaceSimulator
from simulator.strategy_generator import (
    generate_strategies
)

context = get_race_context(
    season=2023,
    gp_name="Bahrain Grand Prix"
)

simulator = RaceSimulator()

strategies = generate_strategies()

for strategy in strategies:

    result = simulator.simulate_strategy(
        strategy=strategy,
        race_context=context
    )

    print(result)

{'strategy': ['SOFT', 'HARD'], 'race_progresses': [0.0, 0.14], 'predicted_stints': [8, 49], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 1, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent'}
{'strategy': ['MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.211], 'predicted_stints': [12, 45], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 1, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent'}
{'strategy': ['HARD', 'MEDIUM'], 'race_progresses': [0.0, 0.228], 'predicted_stints': [13, 44], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 1, 'valid': True, 'final_compound': 'MEDIUM', 'circuit_type': 'Permanent'}
{'strategy': ['SOFT', 'HARD', 'HARD'], 'race_progresses': [0.0, 0.14, 0.386], 'predicted_stints': [8, 14, 35], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent'}
{'strategy': ['MEDIUM', 'HARD', 'HARD'], 'race_progresses': [0.0, 0.211, 0.509], 'predicted_stints': [12, 17, 28], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent'}
{'strategy': ['SOFT', 'SOFT', 'HARD'], 'race_progresses': [0.0, 0.14, 0.351], 'predicted_stints': [8, 12, 37], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent'}
{'strategy': ['MEDIUM', 'MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.211, 0.491], 'predicted_stints': [12, 16, 29], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent'}
{'strategy': ['SOFT', 'HARD', 'SOFT'], 'race_progresses': [0.0, 0.14, 0.386], 'predicted_stints': [8, 14, 35], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 2, 'valid': True, 'final_compound': 'SOFT', 'circuit_type': 'Permanent'}
{'strategy': ['MEDIUM', 'HARD', 'SOFT'], 'race_progresses': [0.0, 0.211, 0.509], 'predicted_stints': [12, 17, 28], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 2, 'valid': True, 'final_compound': 'SOFT', 'circuit_type': 'Permanent'}
{'strategy': ['SOFT', 'MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.14, 0.386], 'predicted_stints': [8, 14, 35], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent'}
{'strategy': ['MEDIUM', 'SOFT', 'HARD'], 'race_progresses': [0.0, 0.211, 0.474], 'predicted_stints': [12, 15, 30], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent'}

In [1]:
import sys
import os
sys.path.append(os.path.abspath('..'))

from simulator.race_context import get_race_context
from simulator.race_simulator import RaceSimulator
from simulator.strategy_generator import (
    evaluate_strategies
)
context = get_race_context(
    season=2024,
    gp_name="Bahrain Grand Prix"
)

simulator = RaceSimulator()

results = evaluate_strategies(
    simulator,
    context
)

print(len(results))

for result in results:
    print(result)

11
{'strategy': ['SOFT', 'HARD'], 'race_progresses': [0.0, 0.193], 'predicted_stints': [11, 46], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 1, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent', 'balance_score': 17.5}
{'strategy': ['MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.246], 'predicted_stints': [14, 43], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 1, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent', 'balance_score': 14.5}
{'strategy': ['HARD', 'MEDIUM'], 'race_progresses': [0.0, 0.246], 'predicted_stints': [14, 43], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 1, 'valid': True, 'final_compound': 'MEDIUM', 'circuit_type': 'Permanent', 'balance_score': 14.5}
{'strategy': ['SOFT', 'HARD', 'HARD'], 'race_progresses': [0.0, 0.193, 0.491], 'predicted_stints': [11, 17, 29], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent', 'balance_score': 7.48}
{'strategy': ['MEDIUM', 'HARD', 'HARD'], 'race_progresses': [0.0, 0.246, 0.561], 'predicted_stints': [14, 18, 25], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent', 'balance_score': 4.55}
{'strategy': ['SOFT', 'SOFT', 'HARD'], 'race_progresses': [0.0, 0.193, 0.474], 'predicted_stints': [11, 16, 30], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent', 'balance_score': 8.04}
{'strategy': ['MEDIUM', 'MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.246, 0.544], 'predicted_stints': [14, 17, 26], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent', 'balance_score': 5.1}
{'strategy': ['SOFT', 'HARD', 'SOFT'], 'race_progresses': [0.0, 0.193, 0.491], 'predicted_stints': [11, 17, 29], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 2, 'valid': True, 'final_compound': 'SOFT', 'circuit_type': 'Permanent', 'balance_score': 7.48}
{'strategy': ['MEDIUM', 'HARD', 'SOFT'], 'race_progresses': [0.0, 0.246, 0.561], 'predicted_stints': [14, 18, 25], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 2, 'valid': True, 'final_compound': 'SOFT', 'circuit_type': 'Permanent', 'balance_score': 4.55}
{'strategy': ['SOFT', 'MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.193, 0.474], 'predicted_stints': [11, 16, 30], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent', 'balance_score': 8.04}
{'strategy': ['MEDIUM', 'SOFT', 'HARD'], 'race_progresses': [0.0, 0.246, 0.526], 'predicted_stints': [14, 16, 27], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent', 'balance_score': 5.72}

In [1]:
import sys
import os
sys.path.append(os.path.abspath('..'))

from simulator.race_context import get_race_context
from simulator.race_simulator import RaceSimulator
from simulator.strategy_generator import (
    evaluate_strategies
)
context = get_race_context(
    season=2024,
    gp_name="Bahrain Grand Prix"
)

simulator = RaceSimulator()

results = evaluate_strategies(
    simulator,
    context
)

print(len(results))

for result in results:
    print(result)

5
{'strategy': ['MEDIUM', 'HARD', 'HARD'], 'race_progresses': [0.0, 0.246, 0.561], 'predicted_stints': [14, 18, 25], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent', 'balance_score': 4.55}
{'strategy': ['MEDIUM', 'HARD', 'SOFT'], 'race_progresses': [0.0, 0.246, 0.561], 'predicted_stints': [14, 18, 25], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 2, 'valid': True, 'final_compound': 'SOFT', 'circuit_type': 'Permanent', 'balance_score': 4.55}
{'strategy': ['MEDIUM', 'MEDIUM', 'HARD'], 'race_progresses': [0.0, 0.246, 0.544], 'predicted_stints': [14, 17, 26], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent', 'balance_score': 5.1}
{'strategy': ['MEDIUM', 'SOFT', 'HARD'], 'race_progresses': [0.0, 0.246, 0.526], 'predicted_stints': [14, 16, 27], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent', 'balance_score': 5.72}
{'strategy': ['SOFT', 'HARD', 'HARD'], 'race_progresses': [0.0, 0.193, 0.491], 'predicted_stints': [11, 17, 29], 'total_laps': 57, 'race_laps': 57, 'coverage_margin': 0, 'pit_stops': 2, 'valid': True, 'final_compound': 'HARD', 'circuit_type': 'Permanent', 'balance_score': 7.48}

In [3]:
import pandas as pd

# Absolute paths
path_2023 = (
    "C:/Users/VANSH/Formula1/datasets/2023/"
    "final_merged_2023_data.csv"
)

path_2024 = (
    "C:/Users/VANSH/Formula1/datasets/2024/"
    "final_merged_2024_data.csv"
)

path_2025 = (
    "C:/Users/VANSH/Formula1/datasets/2025/"
    "merged_2025_data_simplified_sorted.csv"
)


# Load lap-level datasets
df_2023 = pd.read_csv(path_2023)
df_2024 = pd.read_csv(path_2024)
df_2025 = pd.read_csv(path_2025)


def inspect_stint_lengths(df, season):
    # Restrict to race sessions
    session_column = "SessionType" if "SessionType" in df.columns else "Session"
    race_data = df[df[session_column] == "R"].copy()

    # Calculate both versions of stint length
    comparison = (
        race_data.groupby(
            ["GP", "Driver", "Stint", "Compound"],
            as_index=False
        )
        .agg(
            OldStintLength=("TyreLife", "max"),
            CorrectedStintLength=("LapNumber", "nunique")
        )
    )

    comparison["Difference"] = (
        comparison["OldStintLength"]
        - comparison["CorrectedStintLength"]
    )

    print(f"\n========== {season} ==========")
    print("Number of stints:", len(comparison))

    print("\nOld target summary:")
    print(comparison["OldStintLength"].describe())

    print("\nCorrected target summary:")
    print(comparison["CorrectedStintLength"].describe())

    print("\nDifference summary:")
    print(comparison["Difference"].describe())

    print(
        "\nStints where the two calculations differ:",
        (comparison["Difference"] != 0).sum()
    )

    print("\nLargest differences:")
    print(
        comparison.sort_values(
            "Difference",
            ascending=False
        ).head(10).to_string(index=False)
    )

    return comparison


comparison_2023 = inspect_stint_lengths(df_2023, 2023)
comparison_2024 = inspect_stint_lengths(df_2024, 2024)
comparison_2025 = inspect_stint_lengths(df_2025, 2025)

C:\Users\VANSH\AppData\Local\Temp\ipykernel_11748\3340609243.py:21: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2023 = pd.read_csv(path_2023)
C:\Users\VANSH\AppData\Local\Temp\ipykernel_11748\3340609243.py:23: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2025 = pd.read_csv(path_2025)

========== 2023 ==========
Number of stints: 1198

Old target summary:
count    1198.000000
mean       19.899833
std        11.135453
min         1.000000
25%        13.000000
50%        19.000000
75%        26.000000
max        58.000000
Name: OldStintLength, dtype: float64

Corrected target summary:
count    1198.000000
mean       18.765442
std        11.151913
min         1.000000
25%        11.000000
50%        18.000000
75%        25.000000
max        58.000000
Name: CorrectedStintLength, dtype: float64

Difference summary:
count    1198.000000
mean        1.134391
std         2.088550
min         0.000000
25%         0.000000
50%         0.000000
75%         2.000000
max        25.000000
Name: Difference, dtype: float64

Stints where the two calculations differ: 417

Largest differences:
                GP Driver  Stint     Compound  OldStintLength  CorrectedStintLength  Difference
Spanish Grand Prix    LEC      3         HARD              50                    25          25
  Dutch Grand Prix    SAI      5 INTERMEDIATE              18                     3          15
  Dutch Grand Prix    NOR      7 INTERMEDIATE              20                     7          13
  Dutch Grand Prix    VER      5 INTERMEDIATE              14                     2          12
  Dutch Grand Prix    RUS      5 INTERMEDIATE              15                     3          12
  Qatar Grand Prix    LEC      1       MEDIUM              20                     9          11
  Qatar Grand Prix    GAS      1       MEDIUM              18                     8          10
  Qatar Grand Prix    HUL      1       MEDIUM              20                    10          10
  Qatar Grand Prix    NOR      1       MEDIUM              20                    10          10
  Qatar Grand Prix    OCO      1       MEDIUM              17                     7          10

========== 2024 ==========
Number of stints: 1229

Old target summary:
count    1229.000000
mean       21.991863
std        11.966427
min         1.000000
25%        13.000000
50%        21.000000
75%        29.000000
max        78.000000
Name: OldStintLength, dtype: float64

Corrected target summary:
count    1229.000000
mean       21.287225
std        11.934526
min         1.000000
25%        13.000000
50%        20.000000
75%        28.000000
max        76.000000
Name: CorrectedStintLength, dtype: float64

Difference summary:
count    1229.000000
mean        0.704638
std         1.594929
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max        15.000000
Name: Difference, dtype: float64

Stints where the two calculations differ: 353

Largest differences:
                       GP Driver  Stint Compound  OldStintLength  CorrectedStintLength  Difference
     São Paulo Grand Prix    LAW      2      WET              18                     3          15
Emilia Romagna Grand Prix    ALB      4   MEDIUM              19                     5          14
         Qatar Grand Prix    HAM      5     HARD              23                    10          13
         Qatar Grand Prix    MAG      4     HARD              30                    19          11
     Las Vegas Grand Prix    OCO      2   MEDIUM              12                     1          11
         Qatar Grand Prix    NOR      5     HARD              22                    12          10
         Qatar Grand Prix    ALO      4   MEDIUM              27                    18           9
         Qatar Grand Prix    BOT      4   MEDIUM              30                    21           9
         Qatar Grand Prix    MAG      3     HARD              10                     1           9
       Chinese Grand Prix    NOR      2     HARD              34                    26           8

========== 2025 ==========
Number of stints: 1228

Old target summary:
count    1228.000000
mean       22.698697
std        11.309404
min         0.000000
25%        14.000000
50%        23.000000
75%        30.000000
max        72.000000
Name: OldStintLength, dtype: float64

Corrected target summary:
count    1228.000000
mean       20.947068
std        11.723435
min         1.000000
25%        12.000000
50%        21.000000
75%        28.000000
max        72.000000
Name: CorrectedStintLength, dtype: float64

Difference summary:
count    1228.000000
mean        1.751629
std         5.233056
min       -18.000000
25%         0.000000
50%         0.000000
75%         2.000000
max        54.000000
Name: Difference, dtype: float64

Stints where the two calculations differ: 432

Largest differences:
                 GP Driver  Stint Compound  OldStintLength  CorrectedStintLength  Difference
Canadian Grand Prix    COL    5.0     HARD              55                     1          54
Canadian Grand Prix    COL    4.0     HARD              54                     1          53
Canadian Grand Prix    COL    3.0     HARD              53                     1          52
Canadian Grand Prix    HUL    6.0     HARD              51                     1          50
Canadian Grand Prix    HUL    5.0     HARD              50                     1          49
Canadian Grand Prix    HUL    4.0     HARD              49                     1          48
Canadian Grand Prix    HUL    3.0     HARD              48                     1          47
Canadian Grand Prix    VER    6.0     HARD              33                     1          32
Canadian Grand Prix    VER    5.0     HARD              32                     1          31
Canadian Grand Prix    ANT    6.0     HARD              32                     1          31

In [4]:
# --------------------------------------------------
# Inspect Canadian GP data for Colapinto and Hulkenberg
# --------------------------------------------------

import pandas as pd

diagnostic_columns = [
    "GP",
    "Driver",
    "DriverNumber",
    "Session",
    "SessionType",
    "LapNumber",
    "Stint",
    "Compound",
    "TyreLife",
    "FreshTyre",
    "PitInTime",
    "PitOutTime",
    "TrackStatus",
    "Time",
    "Date",
    "RoundNumber"
]

# Keep only columns that exist in this dataset.
diagnostic_columns = [
    col for col in diagnostic_columns
    if col in df_2025.columns
]

race_data = df_2025[
    df_2025["SessionType"].astype(str).str.upper().eq("R")
].copy()

canadian_data = race_data[
    race_data["GP"].astype(str).str.contains(
        "Canadian Grand Prix",
        case=False,
        na=False
    )
    & race_data["Driver"].astype(str).str.upper().isin(["COL", "HUL"])
].copy()

# Display the lap-by-lap records.
print("========== RAW LAP RECORDS ==========")

print(
    canadian_data[diagnostic_columns]
    .sort_values(["Driver", "LapNumber"])
    .to_string(index=False)
)


# --------------------------------------------------
# Summarise the recorded stints
# --------------------------------------------------

print("\n========== STINT SUMMARY ==========")

stint_summary = (
    canadian_data.groupby(
        ["Driver", "GP", "Stint", "Compound"],
        dropna=False,
        as_index=False
    )
    .agg(
        RecordedRows=("LapNumber", "size"),
        DistinctLaps=("LapNumber", "nunique"),
        FirstLap=("LapNumber", "min"),
        LastLap=("LapNumber", "max"),
        MinTyreLife=("TyreLife", "min"),
        MaxTyreLife=("TyreLife", "max"),
        FreshTyreValues=("FreshTyre", "nunique")
    )
)

print(stint_summary.to_string(index=False))

========== RAW LAP RECORDS ==========
                 GP Driver  DriverNumber SessionType  LapNumber  Stint Compound  TyreLife  FreshTyre              PitInTime             PitOutTime  TrackStatus       Date  RoundNumber
Canadian Grand Prix    COL            43           R        1.0    1.0   MEDIUM         6          0                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R        2.0    1.0   MEDIUM         7          0                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R        3.0    1.0   MEDIUM         8          0                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R        4.0    1.0   MEDIUM         9          0                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R        5.0    1.0   MEDIUM        10          0                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R        6.0    1.0   MEDIUM        11          0                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R        7.0    1.0   MEDIUM        12          0                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R        8.0    1.0   MEDIUM        13          0                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R        9.0    1.0   MEDIUM        14          0                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       10.0    1.0   MEDIUM        15          0                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       11.0    1.0   MEDIUM        16          0                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       12.0    1.0   MEDIUM        17          0                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       13.0    1.0   MEDIUM        18          0                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       14.0    1.0   MEDIUM        19          0 0 days 01:16:12.702000                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       15.0    2.0     HARD         1          1                    NaN 0 days 01:16:37.249000          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       16.0    2.0     HARD         2          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       17.0    2.0     HARD         3          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       18.0    2.0     HARD         4          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       19.0    2.0     HARD         5          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       20.0    2.0     HARD         6          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       21.0    2.0     HARD         7          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       22.0    2.0     HARD         8          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       23.0    2.0     HARD         9          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       24.0    2.0     HARD        10          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       25.0    2.0     HARD        11          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       26.0    2.0     HARD        12          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       27.0    2.0     HARD        13          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       28.0    2.0     HARD        14          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       29.0    2.0     HARD        15          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       30.0    2.0     HARD        16          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       31.0    2.0     HARD        17          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       32.0    2.0     HARD        18          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       33.0    2.0     HARD        19          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       34.0    2.0     HARD        20          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       35.0    2.0     HARD        21          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       36.0    2.0     HARD        22          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       37.0    2.0     HARD        23          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       38.0    2.0     HARD        24          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       39.0    2.0     HARD        25          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       40.0    2.0     HARD        26          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       41.0    2.0     HARD        27          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       42.0    2.0     HARD        28          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       43.0    2.0     HARD        29          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       44.0    2.0     HARD        30          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       45.0    2.0     HARD        31          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       46.0    2.0     HARD        32          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       47.0    2.0     HARD        33          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       48.0    2.0     HARD        34          1                    NaN                    NaN         12.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       49.0    2.0     HARD        35          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       50.0    2.0     HARD        36          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       51.0    2.0     HARD        37          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       52.0    2.0     HARD        38          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       53.0    2.0     HARD        39          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       54.0    2.0     HARD        40          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       55.0    2.0     HARD        41          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       56.0    2.0     HARD        42          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       57.0    2.0     HARD        43          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       58.0    2.0     HARD        44          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       59.0    2.0     HARD        45          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       60.0    2.0     HARD        46          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       61.0    2.0     HARD        47          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       62.0    2.0     HARD        48          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       63.0    2.0     HARD        49          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       64.0    2.0     HARD        50          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       65.0    2.0     HARD        51          1                    NaN                    NaN         12.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       66.0    2.0     HARD        52          1 0 days 02:23:58.429000                    NaN         24.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       67.0    3.0     HARD        53          0 0 days 02:25:55.364000 0 days 02:24:16.616000          4.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       68.0    4.0     HARD        54          0 0 days 02:27:41.206000 0 days 02:26:13.533000          4.0 2025-06-15           10
Canadian Grand Prix    COL            43           R       69.0    5.0     HARD        55          0                    NaN 0 days 02:27:59.393000          4.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R        1.0    1.0   MEDIUM         1          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R        2.0    1.0   MEDIUM         2          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R        3.0    1.0   MEDIUM         3          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R        4.0    1.0   MEDIUM         4          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R        5.0    1.0   MEDIUM         5          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R        6.0    1.0   MEDIUM         6          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R        7.0    1.0   MEDIUM         7          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R        8.0    1.0   MEDIUM         8          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R        9.0    1.0   MEDIUM         9          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       10.0    1.0   MEDIUM        10          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       11.0    1.0   MEDIUM        11          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       12.0    1.0   MEDIUM        12          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       13.0    1.0   MEDIUM        13          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       14.0    1.0   MEDIUM        14          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       15.0    1.0   MEDIUM        15          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       16.0    1.0   MEDIUM        16          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       17.0    1.0   MEDIUM        17          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       18.0    1.0   MEDIUM        18          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       19.0    1.0   MEDIUM        19          1 0 days 01:22:39.677000                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       20.0    2.0     HARD         1          1                    NaN 0 days 01:23:03.099000          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       21.0    2.0     HARD         2          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       22.0    2.0     HARD         3          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       23.0    2.0     HARD         4          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       24.0    2.0     HARD         5          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       25.0    2.0     HARD         6          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       26.0    2.0     HARD         7          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       27.0    2.0     HARD         8          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       28.0    2.0     HARD         9          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       29.0    2.0     HARD        10          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       30.0    2.0     HARD        11          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       31.0    2.0     HARD        12          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       32.0    2.0     HARD        13          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       33.0    2.0     HARD        14          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       34.0    2.0     HARD        15          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       35.0    2.0     HARD        16          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       36.0    2.0     HARD        17          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       37.0    2.0     HARD        18          1                    NaN                    NaN          1.0 2025-06-15           10
Canadian Grand Prix    HUL            27           R       38.0    2.0     HARD        19          1                    NaN                    NaN          1.0 2025-06-15           10

In [6]:
import pandas as pd


def find_suspicious_stint_transitions(df, season):
    session_column = (
    "SessionType"
    if "SessionType" in df.columns
    else "Session"
)

    race = df[
    df[session_column].astype(str).str.upper().eq("R")
].copy()

    # Normalise numeric fields for comparisons.
    for col in ["LapNumber", "Stint", "TyreLife"]:
        race[col] = pd.to_numeric(
            race[col],
            errors="coerce"
        )

    race = race.sort_values(
        ["GP", "Driver", "LapNumber"]
    ).copy()

    group_keys = ["GP", "Driver"]

    # Capture the preceding race-lap record for each driver and GP.
    columns_to_compare = [
        "LapNumber",
        "Stint",
        "Compound",
        "TyreLife",
        "FreshTyre"
    ]

    for col in columns_to_compare:
        race[f"Previous_{col}"] = (
            race.groupby(group_keys)[col].shift(1)
        )

    consecutive_laps = (
        race["LapNumber"] - race["Previous_LapNumber"]
    ).eq(1)

    stint_changed = (
        race["Stint"] != race["Previous_Stint"]
    )

    same_compound = (
        race["Compound"].fillna("").astype(str)
        == race["Previous_Compound"].fillna("").astype(str)
    )

    tyre_age_increased_by_one = (
        race["TyreLife"] - race["Previous_TyreLife"]
    ).eq(1)

    suspicious = race[
        consecutive_laps
        & stint_changed
        & same_compound
        & tyre_age_increased_by_one
    ].copy()

    output_columns = [
        "GP",
        "Driver",
        "Previous_LapNumber",
        "LapNumber",
        "Previous_Stint",
        "Stint",
        "Previous_Compound",
        "Compound",
        "Previous_TyreLife",
        "TyreLife",
        "Previous_FreshTyre",
        "FreshTyre",
        "PitInTime",
        "PitOutTime"
    ]

    output_columns = [
        col for col in output_columns
        if col in suspicious.columns
    ]

    print(f"\n========== {season} ==========")
    print("Total race-lap records:", len(race))
    print(
        "Suspicious consecutive transitions:",
        len(suspicious)
    )

    if not suspicious.empty:
        print("\nExamples:")
        print(
            suspicious[output_columns]
            .head(25)
            .to_string(index=False)
        )

        print("\nAffected GPs:")
        print(
            suspicious.groupby("GP")
            .size()
            .sort_values(ascending=False)
            .head(15)
        )

    return suspicious


suspicious_2023 = find_suspicious_stint_transitions(
    df_2023, 2023
)

suspicious_2024 = find_suspicious_stint_transitions(
    df_2024, 2024
)

suspicious_2025 = find_suspicious_stint_transitions(
    df_2025, 2025
)

========== 2023 ==========
Total race-lap records: 22481
Suspicious consecutive transitions: 20

Examples:
                 GP Driver  Previous_LapNumber  LapNumber  Previous_Stint  Stint Previous_Compound Compound  Previous_TyreLife  TyreLife  Previous_FreshTyre  FreshTyre
Austrian Grand Prix    ALB                 2.0          3             1.0      2            MEDIUM   MEDIUM                2.0         3                 1.0          0
Austrian Grand Prix    ALO                 2.0          3             1.0      2              HARD     HARD                2.0         3                 1.0          0
Austrian Grand Prix    BOT                 2.0          3             1.0      2              HARD     HARD                2.0         3                 1.0          0
Austrian Grand Prix    DEV                 2.0          3             1.0      2            MEDIUM   MEDIUM                2.0         3                 1.0          0
Austrian Grand Prix    GAS                 2.0          3             1.0      2            MEDIUM   MEDIUM                2.0         3                 1.0          0
Austrian Grand Prix    HAM                 2.0          3             1.0      2            MEDIUM   MEDIUM                2.0         3                 1.0          0
Austrian Grand Prix    HUL                 2.0          3             1.0      2            MEDIUM   MEDIUM                5.0         6                 0.0          0
Austrian Grand Prix    LEC                 2.0          3             1.0      2            MEDIUM   MEDIUM                2.0         3                 1.0          0
Austrian Grand Prix    NOR                 2.0          3             1.0      2            MEDIUM   MEDIUM                2.0         3                 1.0          0
Austrian Grand Prix    OCO                 2.0          3             1.0      2            MEDIUM   MEDIUM                2.0         3                 1.0          0
Austrian Grand Prix    PER                 2.0          3             1.0      2            MEDIUM   MEDIUM                2.0         3                 1.0          0
Austrian Grand Prix    PIA                 2.0          3             1.0      2            MEDIUM   MEDIUM                2.0         3                 1.0          0
Austrian Grand Prix    RUS                 2.0          3             1.0      2            MEDIUM   MEDIUM                2.0         3                 1.0          0
Austrian Grand Prix    SAI                 2.0          3             1.0      2            MEDIUM   MEDIUM                2.0         3                 1.0          0
Austrian Grand Prix    SAR                 2.0          3             1.0      2            MEDIUM   MEDIUM                2.0         3                 1.0          0
Austrian Grand Prix    STR                 2.0          3             1.0      2            MEDIUM   MEDIUM                2.0         3                 1.0          0
Austrian Grand Prix    TSU                 2.0          3             2.0      3              HARD     HARD                1.0         2                 1.0          0
Austrian Grand Prix    VER                 2.0          3             1.0      2            MEDIUM   MEDIUM                2.0         3                 1.0          0
Austrian Grand Prix    ZHO                 2.0          3             1.0      2            MEDIUM   MEDIUM                2.0         3                 1.0          0
 Bahrain Grand Prix    OCO                15.0         16             2.0      3              HARD     HARD                3.0         4                 1.0          0

Affected GPs:
GP
Austrian Grand Prix    19
Bahrain Grand Prix      1
dtype: int64

========== 2024 ==========
Total race-lap records: 26162
Suspicious consecutive transitions: 12

Examples:
                       GP Driver  Previous_LapNumber  LapNumber  Previous_Stint  Stint Previous_Compound Compound  Previous_TyreLife  TyreLife  Previous_FreshTyre  FreshTyre
     Abu Dhabi Grand Prix    LAW                24.0         25             2.0      3              HARD     HARD                1.0         2                 1.0          0
     Abu Dhabi Grand Prix    LAW                29.0         30             3.0      4              HARD     HARD                6.0         7                 0.0          0
Emilia Romagna Grand Prix    ALB                23.0         24             3.0      4            MEDIUM   MEDIUM               14.0        15                 0.0          0
      Japanese Grand Prix    ZHO                11.0         12             3.0      4              HARD     HARD                4.0         5                 1.0          0
     Las Vegas Grand Prix    OCO                11.0         12             1.0      2            MEDIUM   MEDIUM               11.0        12                 1.0          0
         Miami Grand Prix    MAG                31.0         32             3.0      4            MEDIUM   MEDIUM                3.0         4                 1.0          0
         Qatar Grand Prix    HAM                47.0         48             4.0      5              HARD     HARD               13.0        14                 0.0          0
         Qatar Grand Prix    HUL                36.0         37             3.0      4            MEDIUM   MEDIUM                5.0         6                 1.0          0
         Qatar Grand Prix    LAW                37.0         38             3.0      4              HARD     HARD                2.0         3                 0.0          0
         Qatar Grand Prix    MAG                36.0         37             2.0      3              HARD     HARD                9.0        10                 1.0          0
         Qatar Grand Prix    NOR                45.0         46             4.0      5              HARD     HARD               10.0        11                 0.0          0
         Qatar Grand Prix    SAI                36.0         37             2.0      3              HARD     HARD                2.0         3                 1.0          0

Affected GPs:
GP
Qatar Grand Prix             6
Abu Dhabi Grand Prix         2
Emilia Romagna Grand Prix    1
Japanese Grand Prix          1
Las Vegas Grand Prix         1
Miami Grand Prix             1
dtype: int64

========== 2025 ==========
Total race-lap records: 25723
Suspicious consecutive transitions: 52

Examples:
                 GP Driver  Previous_LapNumber  LapNumber  Previous_Stint  Stint Previous_Compound Compound  Previous_TyreLife  TyreLife  Previous_FreshTyre  FreshTyre              PitInTime             PitOutTime
Canadian Grand Prix    ALO                66.0       67.0             3.0    4.0              HARD     HARD               17.0        18                 0.0          0 0 days 02:25:03.867000 0 days 02:23:28.382000
Canadian Grand Prix    ALO                67.0       68.0             4.0    5.0              HARD     HARD               18.0        19                 0.0          0 0 days 02:26:43.158000 0 days 02:25:22.095000
Canadian Grand Prix    ALO                68.0       69.0             5.0    6.0              HARD     HARD               19.0        20                 0.0          0 0 days 02:28:19.831000 0 days 02:27:01.471000
Canadian Grand Prix    ALO                69.0       70.0             6.0    7.0              HARD     HARD               20.0        21                 0.0          0                    NaN 0 days 02:28:38.065000
Canadian Grand Prix    ANT                67.0       68.0             3.0    4.0              HARD     HARD               29.0        30                 1.0          0 0 days 02:25:26.109000 0 days 02:23:41.725000
Canadian Grand Prix    ANT                68.0       69.0             4.0    5.0              HARD     HARD               30.0        31                 0.0          0 0 days 02:27:30.534000 0 days 02:25:45.036000
Canadian Grand Prix    ANT                69.0       70.0             5.0    6.0              HARD     HARD               31.0        32                 0.0          0                    NaN 0 days 02:27:48.799000
Canadian Grand Prix    BEA                67.0       68.0             3.0    4.0              SOFT     SOFT                1.0         2                 1.0          0 0 days 02:27:37.362000 0 days 02:26:08.505000
Canadian Grand Prix    BEA                68.0       69.0             4.0    5.0              SOFT     SOFT                2.0         3                 0.0          0                    NaN 0 days 02:27:55.534000
Canadian Grand Prix    BOR                66.0       67.0             2.0    3.0            MEDIUM   MEDIUM               17.0        18                 1.0          0 0 days 02:25:56.926000 0 days 02:24:17.585000
Canadian Grand Prix    BOR                67.0       68.0             3.0    4.0            MEDIUM   MEDIUM               18.0        19                 0.0          0 0 days 02:27:42.831000 0 days 02:26:15.264000
Canadian Grand Prix    BOR                68.0       69.0             4.0    5.0            MEDIUM   MEDIUM               19.0        20                 0.0          0                    NaN 0 days 02:28:01.143000
Canadian Grand Prix    COL                66.0       67.0             2.0    3.0              HARD     HARD               52.0        53                 1.0          0 0 days 02:25:55.364000 0 days 02:24:16.616000
Canadian Grand Prix    COL                67.0       68.0             3.0    4.0              HARD     HARD               53.0        54                 0.0          0 0 days 02:27:41.206000 0 days 02:26:13.533000
Canadian Grand Prix    COL                68.0       69.0             4.0    5.0              HARD     HARD               54.0        55                 0.0          0                    NaN 0 days 02:27:59.393000
Canadian Grand Prix    GAS                66.0       67.0             2.0    3.0            MEDIUM   MEDIUM               13.0        14                 1.0          0 0 days 02:25:58.223000 0 days 02:24:20.976000
Canadian Grand Prix    GAS                67.0       68.0             3.0    4.0            MEDIUM   MEDIUM               14.0        15                 0.0          0 0 days 02:27:44.940000 0 days 02:26:16.438000
Canadian Grand Prix    GAS                68.0       69.0             4.0    5.0            MEDIUM   MEDIUM               15.0        16                 0.0          0                    NaN 0 days 02:28:03.065000
Canadian Grand Prix    HAD                67.0       68.0             3.0    4.0              SOFT     SOFT                4.0         5                 0.0          0 0 days 02:27:47.503000 0 days 02:26:22.830000
Canadian Grand Prix    HAD                68.0       69.0             4.0    5.0              SOFT     SOFT                5.0         6                 0.0          0                    NaN 0 days 02:28:05.800000
Canadian Grand Prix    HAM                67.0       68.0             3.0    4.0              HARD     HARD               22.0        23                 1.0          0 0 days 02:26:13.122000 0 days 02:24:40.745000
Canadian Grand Prix    HAM                68.0       69.0             4.0    5.0              HARD     HARD               23.0        24                 0.0          0 0 days 02:27:50.909000 0 days 02:26:31.377000
Canadian Grand Prix    HAM                69.0       70.0             5.0    6.0              HARD     HARD               24.0        25                 0.0          0                    NaN 0 days 02:28:09.081000
Canadian Grand Prix    HUL                66.0       67.0             2.0    3.0              HARD     HARD               47.0        48                 1.0          0 0 days 02:25:06.621000 0 days 02:23:32.538000
Canadian Grand Prix    HUL                67.0       68.0             3.0    4.0              HARD     HARD               48.0        49                 0.0          0 0 days 02:26:45.690000 0 days 02:25:24.880000

Affected GPs:
GP
Canadian Grand Prix       49
Mexico City Grand Prix     1
Qatar Grand Prix           1
Spanish Grand Prix         1
dtype: int64

In [9]:
import pandas as pd

# Inspect the 2023 Austrian Grand Prix
austria = df_2023[
    (df_2023["GP"] == "Austrian Grand Prix")
    & (df_2023["Session"].astype(str).str.upper() == "R")
].copy()

columns = [
    "Driver",
    "LapNumber",
    "Stint",
    "Compound",
    "TyreLife",
    "FreshTyre"
]

# Keep only columns that actually exist
columns = [col for col in columns if col in austria.columns]

austria["LapNumber"] = pd.to_numeric(
    austria["LapNumber"], errors="coerce"
)

austria = austria.sort_values(["Driver", "LapNumber"])

# Inspect the first five laps for every driver
early_laps = austria[austria["LapNumber"] <= 5]

print("========== AUSTRIAN GP: LAPS 1–5 ==========")
print(early_laps[columns].to_string(index=False))

# Compare each driver's lap 2 and lap 3
lap_2 = austria[austria["LapNumber"] == 2].set_index("Driver")
lap_3 = austria[austria["LapNumber"] == 3].set_index("Driver")

common_drivers = lap_2.index.intersection(lap_3.index)

comparison = pd.DataFrame({
    "Stint_Lap2": lap_2.loc[common_drivers, "Stint"],
    "Stint_Lap3": lap_3.loc[common_drivers, "Stint"],
    "Compound_Lap2": lap_2.loc[common_drivers, "Compound"],
    "Compound_Lap3": lap_3.loc[common_drivers, "Compound"],
    "TyreLife_Lap2": lap_2.loc[common_drivers, "TyreLife"],
    "TyreLife_Lap3": lap_3.loc[common_drivers, "TyreLife"],
    "FreshTyre_Lap2": lap_2.loc[common_drivers, "FreshTyre"],
    "FreshTyre_Lap3": lap_3.loc[common_drivers, "FreshTyre"]
})

comparison["StintChanged"] = (
    comparison["Stint_Lap2"] != comparison["Stint_Lap3"]
)

print("\n========== LAP 2 VS LAP 3 ==========")
print(comparison.to_string())

print(
    "\nDrivers with a stint-number change:",
    int(comparison["StintChanged"].sum())
)

========== AUSTRIAN GP: LAPS 1–5 ==========
Driver  LapNumber  Stint Compound  TyreLife  FreshTyre
   ALB          1      1   MEDIUM         1          1
   ALB          2      1   MEDIUM         2          1
   ALB          3      2   MEDIUM         3          0
   ALB          4      2   MEDIUM         4          0
   ALB          5      2   MEDIUM         5          0
   ALO          1      1     HARD         1          1
   ALO          2      1     HARD         2          1
   ALO          3      2     HARD         3          0
   ALO          4      2     HARD         4          0
   ALO          5      2     HARD         5          0
   BOT          1      1     HARD         1          1
   BOT          2      1     HARD         2          1
   BOT          3      2     HARD         3          0
   BOT          4      2     HARD         4          0
   BOT          5      2     HARD         5          0
   DEV          1      1   MEDIUM         1          1
   DEV          2      1   MEDIUM         2          1
   DEV          3      2   MEDIUM         3          0
   DEV          4      2   MEDIUM         4          0
   DEV          5      2   MEDIUM         5          0
   GAS          1      1   MEDIUM         1          1
   GAS          2      1   MEDIUM         2          1
   GAS          3      2   MEDIUM         3          0
   GAS          4      2   MEDIUM         4          0
   GAS          5      2   MEDIUM         5          0
   HAM          1      1   MEDIUM         1          1
   HAM          2      1   MEDIUM         2          1
   HAM          3      2   MEDIUM         3          0
   HAM          4      2   MEDIUM         4          0
   HAM          5      2   MEDIUM         5          0
   HUL          1      1   MEDIUM         4          0
   HUL          2      1   MEDIUM         5          0
   HUL          3      2   MEDIUM         6          0
   HUL          4      2   MEDIUM         7          0
   HUL          5      2   MEDIUM         8          0
   LEC          1      1   MEDIUM         1          1
   LEC          2      1   MEDIUM         2          1
   LEC          3      2   MEDIUM         3          0
   LEC          4      2   MEDIUM         4          0
   LEC          5      2   MEDIUM         5          0
   MAG          1      1     HARD         1          1
   MAG          2      2   MEDIUM         1          1
   MAG          3      3     HARD         1          1
   MAG          4      3     HARD         2          1
   MAG          5      3     HARD         3          1
   NOR          1      1   MEDIUM         1          1
   NOR          2      1   MEDIUM         2          1
   NOR          3      2   MEDIUM         3          0
   NOR          4      2   MEDIUM         4          0
   NOR          5      2   MEDIUM         5          0
   OCO          1      1   MEDIUM         1          1
   OCO          2      1   MEDIUM         2          1
   OCO          3      2   MEDIUM         3          0
   OCO          4      2   MEDIUM         4          0
   OCO          5      2   MEDIUM         5          0
   PER          1      1   MEDIUM         1          1
   PER          2      1   MEDIUM         2          1
   PER          3      2   MEDIUM         3          0
   PER          4      2   MEDIUM         4          0
   PER          5      2   MEDIUM         5          0
   PIA          1      1   MEDIUM         1          1
   PIA          2      1   MEDIUM         2          1
   PIA          3      2   MEDIUM         3          0
   PIA          4      2   MEDIUM         4          0
   PIA          5      2   MEDIUM         5          0
   RUS          1      1   MEDIUM         1          1
   RUS          2      1   MEDIUM         2          1
   RUS          3      2   MEDIUM         3          0
   RUS          4      2   MEDIUM         4          0
   RUS          5      2   MEDIUM         5          0
   SAI          1      1   MEDIUM         1          1
   SAI          2      1   MEDIUM         2          1
   SAI          3      2   MEDIUM         3          0
   SAI          4      2   MEDIUM         4          0
   SAI          5      2   MEDIUM         5          0
   SAR          1      1   MEDIUM         1          1
   SAR          2      1   MEDIUM         2          1
   SAR          3      2   MEDIUM         3          0
   SAR          4      2   MEDIUM         4          0
   SAR          5      2   MEDIUM         5          0
   STR          1      1   MEDIUM         1          1
   STR          2      1   MEDIUM         2          1
   STR          3      2   MEDIUM         3          0
   STR          4      2   MEDIUM         4          0
   STR          5      2   MEDIUM         5          0
   TSU          1      1   MEDIUM         1          1
   TSU          2      2     HARD         1          1
   TSU          3      3     HARD         2          0
   TSU          4      3     HARD         3          0
   TSU          5      3     HARD         4          0
   VER          1      1   MEDIUM         1          1
   VER          2      1   MEDIUM         2          1
   VER          3      2   MEDIUM         3          0
   VER          4      2   MEDIUM         4          0
   VER          5      2   MEDIUM         5          0
   ZHO          1      1   MEDIUM         1          1
   ZHO          2      1   MEDIUM         2          1
   ZHO          3      2   MEDIUM         3          0
   ZHO          4      2   MEDIUM         4          0
   ZHO          5      2   MEDIUM         5          0

========== LAP 2 VS LAP 3 ==========
        Stint_Lap2  Stint_Lap3 Compound_Lap2 Compound_Lap3  TyreLife_Lap2  TyreLife_Lap3  FreshTyre_Lap2  FreshTyre_Lap3  StintChanged
Driver
ALB              1           2        MEDIUM        MEDIUM              2              3               1               0          True
ALO              1           2          HARD          HARD              2              3               1               0          True
BOT              1           2          HARD          HARD              2              3               1               0          True
DEV              1           2        MEDIUM        MEDIUM              2              3               1               0          True
GAS              1           2        MEDIUM        MEDIUM              2              3               1               0          True
HAM              1           2        MEDIUM        MEDIUM              2              3               1               0          True
HUL              1           2        MEDIUM        MEDIUM              5              6               0               0          True
LEC              1           2        MEDIUM        MEDIUM              2              3               1               0          True
MAG              2           3        MEDIUM          HARD              1              1               1               1          True
NOR              1           2        MEDIUM        MEDIUM              2              3               1               0          True
OCO              1           2        MEDIUM        MEDIUM              2              3               1               0          True
PER              1           2        MEDIUM        MEDIUM              2              3               1               0          True
PIA              1           2        MEDIUM        MEDIUM              2              3               1               0          True
RUS              1           2        MEDIUM        MEDIUM              2              3               1               0          True
SAI              1           2        MEDIUM        MEDIUM              2              3               1               0          True
SAR              1           2        MEDIUM        MEDIUM              2              3               1               0          True
STR              1           2        MEDIUM        MEDIUM              2              3               1               0          True
TSU              2           3          HARD          HARD              1              2               1               0          True
VER              1           2        MEDIUM        MEDIUM              2              3               1               0          True
ZHO              1           2        MEDIUM        MEDIUM              2              3               1               0          True

Drivers with a stint-number change: 20

In [11]:
# Step 2: Check for duplicate driver-lap records
# Read-only diagnostic. Does not modify or save any data.

import pandas as pd

austria = df_2023[
    (df_2023["GP"] == "Austrian Grand Prix")
    & (df_2023["Session"].astype(str).str.upper() == "R")
].copy()

key_columns = ["GP", "Driver", "LapNumber", "Session"]

print("========== DUPLICATE DRIVER-LAP CHECK ==========")

duplicate_mask = austria.duplicated(
    subset=key_columns,
    keep=False
)

duplicates = austria.loc[duplicate_mask].sort_values(
    ["Driver", "LapNumber"]
)

print("Total rows in Austrian GP race data:", len(austria))
print("Rows involved in duplicate keys:", len(duplicates))

if duplicates.empty:
    print("\nNo duplicate driver-lap keys found.")
else:
    print("\nDuplicate records:")
    print(duplicates[key_columns + [
        "Stint", "Compound", "TyreLife", "FreshTyre"
    ]].to_string(index=False))

========== DUPLICATE DRIVER-LAP CHECK ==========
Total rows in Austrian GP race data: 1352
Rows involved in duplicate keys: 0

No duplicate driver-lap keys found.

In [12]:
import pandas as pd

source_path = "C:/Users/VANSH/Formula1/datasets/2023/final_merged_2023_data.csv"

source_2023 = pd.read_csv(source_path)

print("========== SOURCE DATA COLUMNS ==========")
print(source_2023.columns.tolist())

print("\n========== SOURCE DATA SHAPE ==========")
print(source_2023.shape)

print("\n========== AUSTRIAN GP: SOURCE ROWS ==========")

austria_source = source_2023[
    (source_2023["GP"] == "Austrian Grand Prix")
    & (source_2023["Session"].astype(str).str.upper() == "R")
].copy()

austria_source["LapNumber"] = pd.to_numeric(
    austria_source["LapNumber"], errors="coerce"
)

early_source = austria_source[
    austria_source["LapNumber"].isin([1, 2, 3, 4, 5])
].sort_values(["Driver", "LapNumber"])

check_columns = [
    "Driver",
    "LapNumber",
    "Stint",
    "Compound",
    "TyreLife",
    "FreshTyre"
]

check_columns = [
    col for col in check_columns
    if col in early_source.columns
]

print(early_source[check_columns].to_string(index=False))

========== SOURCE DATA COLUMNS ==========
['Driver', 'DriverNumber', 'LapNumber', 'Stint', 'Compound', 'TyreLife', 'FreshTyre', 'LapTime', 'Sector1Time', 'Sector2Time', 'Sector3Time', 'Team', 'Position', 'DriverTime', 'WeatherTime', 'AirTemp', 'Humidity', 'Pressure', 'Rainfall', 'TrackTemp', 'WindDirection', 'WindSpeed', 'RoundNumber', 'Session', 'Date', 'GP']

========== SOURCE DATA SHAPE ==========
(39877, 26)

========== AUSTRIAN GP: SOURCE ROWS ==========
Driver  LapNumber  Stint Compound  TyreLife  FreshTyre
   ALB          1      1   MEDIUM         1          1
   ALB          2      1   MEDIUM         2          1
   ALB          3      2   MEDIUM         3          0
   ALB          4      2   MEDIUM         4          0
   ALB          5      2   MEDIUM         5          0
   ALO          1      1     HARD         1          1
   ALO          2      1     HARD         2          1
   ALO          3      2     HARD         3          0
   ALO          4      2     HARD         4          0
   ALO          5      2     HARD         5          0
   BOT          1      1     HARD         1          1
   BOT          2      1     HARD         2          1
   BOT          3      2     HARD         3          0
   BOT          4      2     HARD         4          0
   BOT          5      2     HARD         5          0
   DEV          1      1   MEDIUM         1          1
   DEV          2      1   MEDIUM         2          1
   DEV          3      2   MEDIUM         3          0
   DEV          4      2   MEDIUM         4          0
   DEV          5      2   MEDIUM         5          0
   GAS          1      1   MEDIUM         1          1
   GAS          2      1   MEDIUM         2          1
   GAS          3      2   MEDIUM         3          0
   GAS          4      2   MEDIUM         4          0
   GAS          5      2   MEDIUM         5          0
   HAM          1      1   MEDIUM         1          1
   HAM          2      1   MEDIUM         2          1
   HAM          3      2   MEDIUM         3          0
   HAM          4      2   MEDIUM         4          0
   HAM          5      2   MEDIUM         5          0
   HUL          1      1   MEDIUM         4          0
   HUL          2      1   MEDIUM         5          0
   HUL          3      2   MEDIUM         6          0
   HUL          4      2   MEDIUM         7          0
   HUL          5      2   MEDIUM         8          0
   LEC          1      1   MEDIUM         1          1
   LEC          2      1   MEDIUM         2          1
   LEC          3      2   MEDIUM         3          0
   LEC          4      2   MEDIUM         4          0
   LEC          5      2   MEDIUM         5          0
   MAG          1      1     HARD         1          1
   MAG          2      2   MEDIUM         1          1
   MAG          3      3     HARD         1          1
   MAG          4      3     HARD         2          1
   MAG          5      3     HARD         3          1
   NOR          1      1   MEDIUM         1          1
   NOR          2      1   MEDIUM         2          1
   NOR          3      2   MEDIUM         3          0
   NOR          4      2   MEDIUM         4          0
   NOR          5      2   MEDIUM         5          0
   OCO          1      1   MEDIUM         1          1
   OCO          2      1   MEDIUM         2          1
   OCO          3      2   MEDIUM         3          0
   OCO          4      2   MEDIUM         4          0
   OCO          5      2   MEDIUM         5          0
   PER          1      1   MEDIUM         1          1
   PER          2      1   MEDIUM         2          1
   PER          3      2   MEDIUM         3          0
   PER          4      2   MEDIUM         4          0
   PER          5      2   MEDIUM         5          0
   PIA          1      1   MEDIUM         1          1
   PIA          2      1   MEDIUM         2          1
   PIA          3      2   MEDIUM         3          0
   PIA          4      2   MEDIUM         4          0
   PIA          5      2   MEDIUM         5          0
   RUS          1      1   MEDIUM         1          1
   RUS          2      1   MEDIUM         2          1
   RUS          3      2   MEDIUM         3          0
   RUS          4      2   MEDIUM         4          0
   RUS          5      2   MEDIUM         5          0
   SAI          1      1   MEDIUM         1          1
   SAI          2      1   MEDIUM         2          1
   SAI          3      2   MEDIUM         3          0
   SAI          4      2   MEDIUM         4          0
   SAI          5      2   MEDIUM         5          0
   SAR          1      1   MEDIUM         1          1
   SAR          2      1   MEDIUM         2          1
   SAR          3      2   MEDIUM         3          0
   SAR          4      2   MEDIUM         4          0
   SAR          5      2   MEDIUM         5          0
   STR          1      1   MEDIUM         1          1
   STR          2      1   MEDIUM         2          1
   STR          3      2   MEDIUM         3          0
   STR          4      2   MEDIUM         4          0
   STR          5      2   MEDIUM         5          0
   TSU          1      1   MEDIUM         1          1
   TSU          2      2     HARD         1          1
   TSU          3      3     HARD         2          0
   TSU          4      3     HARD         3          0
   TSU          5      3     HARD         4          0
   VER          1      1   MEDIUM         1          1
   VER          2      1   MEDIUM         2          1
   VER          3      2   MEDIUM         3          0
   VER          4      2   MEDIUM         4          0
   VER          5      2   MEDIUM         5          0
   ZHO          1      1   MEDIUM         1          1
   ZHO          2      1   MEDIUM         2          1
   ZHO          3      2   MEDIUM         3          0
   ZHO          4      2   MEDIUM         4          0
   ZHO          5      2   MEDIUM         5          0

C:\Users\VANSH\AppData\Local\Temp\ipykernel_11748\1520580891.py:5: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  source_2023 = pd.read_csv(source_path)

In [13]:
import pandas as pd

# Step 4: Count suspicious stint transitions across all 2023 races.
# Read-only diagnostic. Does not modify or save any data.

data = source_2023.copy()

for col in ["LapNumber", "Stint", "TyreLife"]:
    data[col] = pd.to_numeric(data[col], errors="coerce")

data = data[
    data["Session"].astype(str).str.upper().eq("R")
].copy()

data = data.sort_values(
    ["GP", "Driver", "LapNumber"]
)

grouped = data.groupby(["GP", "Driver"], sort=False)

data["PreviousLap"] = grouped["LapNumber"].shift(1)
data["PreviousStint"] = grouped["Stint"].shift(1)
data["PreviousCompound"] = grouped["Compound"].shift(1)
data["PreviousTyreLife"] = grouped["TyreLife"].shift(1)
data["PreviousFreshTyre"] = grouped["FreshTyre"].shift(1)

# Screen for consecutive laps where:
# - the stint number changes
# - the compound stays the same
# - tyre age increases by exactly one
data["SuspiciousTransition"] = (
    data["LapNumber"].sub(data["PreviousLap"]).eq(1)
    & data["Stint"].ne(data["PreviousStint"])
    & data["Compound"].eq(data["PreviousCompound"])
    & data["TyreLife"].sub(data["PreviousTyreLife"]).eq(1)
)

results = (
    data[data["SuspiciousTransition"]]
    .groupby("GP")
    .size()
    .sort_values(ascending=False)
)

print("========== FLAGGED TRANSITIONS BY GRAND PRIX ==========")
print(results.to_string())

print(
    "\nTotal flagged transitions:",
    int(data["SuspiciousTransition"].sum())
)

print(
    "Grand Prix affected:",
    int(results.size)
)

========== FLAGGED TRANSITIONS BY GRAND PRIX ==========
GP
Austrian Grand Prix    19
Bahrain Grand Prix      1

Total flagged transitions: 20
Grand Prix affected: 2

In [14]:
# Step 5: Inspect every flagged transition in the 2023 source.
# Read-only diagnostic.

import pandas as pd

data = source_2023.copy()

for col in ["LapNumber", "Stint", "TyreLife"]:
    data[col] = pd.to_numeric(data[col], errors="coerce")

data = data[
    data["Session"].astype(str).str.upper().eq("R")
].copy()

data = data.sort_values(["GP", "Driver", "LapNumber"])

grouped = data.groupby(["GP", "Driver"], sort=False)

data["PreviousLap"] = grouped["LapNumber"].shift(1)
data["PreviousStint"] = grouped["Stint"].shift(1)
data["PreviousCompound"] = grouped["Compound"].shift(1)
data["PreviousTyreLife"] = grouped["TyreLife"].shift(1)

flagged = (
    data["LapNumber"].sub(data["PreviousLap"]).eq(1)
    & data["Stint"].ne(data["PreviousStint"])
    & data["Compound"].eq(data["PreviousCompound"])
    & data["TyreLife"].sub(data["PreviousTyreLife"]).eq(1)
)

flagged_rows = data.loc[flagged]

print("========== FLAGGED TRANSITIONS ==========")

for idx in flagged_rows.index:
    row = data.loc[idx]

    driver_rows = data[
        (data["GP"] == row["GP"])
        & (data["Driver"] == row["Driver"])
    ]

    nearby = driver_rows[
        driver_rows["LapNumber"].between(
            row["LapNumber"] - 1,
            row["LapNumber"] + 1
        )
    ]

    print(
        f"\n--- {row['GP']} | {row['Driver']} | "
        f"Transition at lap {row['LapNumber']} ---"
    )

    print(
        nearby[
            [
                "Driver", "LapNumber", "Stint",
                "Compound", "TyreLife", "FreshTyre"
            ]
        ].to_string(index=False)
    )

========== FLAGGED TRANSITIONS ==========

--- Austrian Grand Prix | ALB | Transition at lap 3 ---
Driver  LapNumber  Stint Compound  TyreLife  FreshTyre
   ALB          2      1   MEDIUM         2          1
   ALB          3      2   MEDIUM         3          0
   ALB          4      2   MEDIUM         4          0

--- Austrian Grand Prix | ALO | Transition at lap 3 ---
Driver  LapNumber  Stint Compound  TyreLife  FreshTyre
   ALO          2      1     HARD         2          1
   ALO          3      2     HARD         3          0
   ALO          4      2     HARD         4          0

--- Austrian Grand Prix | BOT | Transition at lap 3 ---
Driver  LapNumber  Stint Compound  TyreLife  FreshTyre
   BOT          2      1     HARD         2          1
   BOT          3      2     HARD         3          0
   BOT          4      2     HARD         4          0

--- Austrian Grand Prix | DEV | Transition at lap 3 ---
Driver  LapNumber  Stint Compound  TyreLife  FreshTyre
   DEV          2      1   MEDIUM         2          1
   DEV          3      2   MEDIUM         3          0
   DEV          4      2   MEDIUM         4          0

--- Austrian Grand Prix | GAS | Transition at lap 3 ---
Driver  LapNumber  Stint Compound  TyreLife  FreshTyre
   GAS          2      1   MEDIUM         2          1
   GAS          3      2   MEDIUM         3          0
   GAS          4      2   MEDIUM         4          0

--- Austrian Grand Prix | HAM | Transition at lap 3 ---
Driver  LapNumber  Stint Compound  TyreLife  FreshTyre
   HAM          2      1   MEDIUM         2          1
   HAM          3      2   MEDIUM         3          0
   HAM          4      2   MEDIUM         4          0

--- Austrian Grand Prix | HUL | Transition at lap 3 ---
Driver  LapNumber  Stint Compound  TyreLife  FreshTyre
   HUL          2      1   MEDIUM         5          0
   HUL          3      2   MEDIUM         6          0
   HUL          4      2   MEDIUM         7          0

--- Austrian Grand Prix | LEC | Transition at lap 3 ---
Driver  LapNumber  Stint Compound  TyreLife  FreshTyre
   LEC          2      1   MEDIUM         2          1
   LEC          3      2   MEDIUM         3          0
   LEC          4      2   MEDIUM         4          0

--- Austrian Grand Prix | NOR | Transition at lap 3 ---
Driver  LapNumber  Stint Compound  TyreLife  FreshTyre
   NOR          2      1   MEDIUM         2          1
   NOR          3      2   MEDIUM         3          0
   NOR          4      2   MEDIUM         4          0

--- Austrian Grand Prix | OCO | Transition at lap 3 ---
Driver  LapNumber  Stint Compound  TyreLife  FreshTyre
   OCO          2      1   MEDIUM         2          1
   OCO          3      2   MEDIUM         3          0
   OCO          4      2   MEDIUM         4          0

--- Austrian Grand Prix | PER | Transition at lap 3 ---
Driver  LapNumber  Stint Compound  TyreLife  FreshTyre
   PER          2      1   MEDIUM         2          1
   PER          3      2   MEDIUM         3          0
   PER          4      2   MEDIUM         4          0

--- Austrian Grand Prix | PIA | Transition at lap 3 ---
Driver  LapNumber  Stint Compound  TyreLife  FreshTyre
   PIA          2      1   MEDIUM         2          1
   PIA          3      2   MEDIUM         3          0
   PIA          4      2   MEDIUM         4          0

--- Austrian Grand Prix | RUS | Transition at lap 3 ---
Driver  LapNumber  Stint Compound  TyreLife  FreshTyre
   RUS          2      1   MEDIUM         2          1
   RUS          3      2   MEDIUM         3          0
   RUS          4      2   MEDIUM         4          0

--- Austrian Grand Prix | SAI | Transition at lap 3 ---
Driver  LapNumber  Stint Compound  TyreLife  FreshTyre
   SAI          2      1   MEDIUM         2          1
   SAI          3      2   MEDIUM         3          0
   SAI          4      2   MEDIUM         4          0

--- Austrian Grand Prix | SAR | Transition at lap 3 ---
Driver  LapNumber  Stint Compound  TyreLife  FreshTyre
   SAR          2      1   MEDIUM         2          1
   SAR          3      2   MEDIUM         3          0
   SAR          4      2   MEDIUM         4          0

--- Austrian Grand Prix | STR | Transition at lap 3 ---
Driver  LapNumber  Stint Compound  TyreLife  FreshTyre
   STR          2      1   MEDIUM         2          1
   STR          3      2   MEDIUM         3          0
   STR          4      2   MEDIUM         4          0

--- Austrian Grand Prix | TSU | Transition at lap 3 ---
Driver  LapNumber  Stint Compound  TyreLife  FreshTyre
   TSU          2      2     HARD         1          1
   TSU          3      3     HARD         2          0
   TSU          4      3     HARD         3          0

--- Austrian Grand Prix | VER | Transition at lap 3 ---
Driver  LapNumber  Stint Compound  TyreLife  FreshTyre
   VER          2      1   MEDIUM         2          1
   VER          3      2   MEDIUM         3          0
   VER          4      2   MEDIUM         4          0

--- Austrian Grand Prix | ZHO | Transition at lap 3 ---
Driver  LapNumber  Stint Compound  TyreLife  FreshTyre
   ZHO          2      1   MEDIUM         2          1
   ZHO          3      2   MEDIUM         3          0
   ZHO          4      2   MEDIUM         4          0

--- Bahrain Grand Prix | OCO | Transition at lap 16 ---
Driver  LapNumber  Stint Compound  TyreLife  FreshTyre
   OCO         15      2     HARD         3          1
   OCO         16      3     HARD         4          0
   OCO         17      3     HARD         5          0

### Correcting Target (Stint Length) across 3 seasons

In [1]:
import pandas as pd
import numpy as np


# ============================================================
# CONFIGURATION
# ============================================================

SEASONS = {
    "2023": {
        "source": (
            "C:/Users/VANSH/Formula1/datasets/2023/"
            "final_merged_2023_data.csv"
        ),
        "master": (
            "C:/Users/VANSH/Formula1/datasets/2023/"
            "master_stint_2023_v3.csv"
        ),
        "output": (
            "C:/Users/VANSH/Formula1/datasets/2023/"
            "master_stint_2023_v4_targetfix.csv"
        ),
    },

    "2024": {
        "source": (
            "C:/Users/VANSH/Formula1/datasets/2024/"
            "final_merged_2024_data.csv"
        ),
        "master": (
            "C:/Users/VANSH/Formula1/datasets/2024/"
            "master_stint_2024_v3.csv"
        ),
        "output": (
            "C:/Users/VANSH/Formula1/datasets/2024/"
            "master_stint_2024_v4_targetfix.csv"
        ),
    },

    "2025": {
        "source": (
            "C:/Users/VANSH/Formula1/datasets/2025/"
            "merged_2025_data_simplified_sorted.csv"
        ),
        "master": (
            "C:/Users/VANSH/Formula1/datasets/2025/"
            "master_stint_2025_v1.csv"
        ),
        "output": (
            "C:/Users/VANSH/Formula1/datasets/2025/"
            "master_stint_2025_v2_targetfix.csv"
        ),
    },
}


KEY_COLUMNS = [
    "GP",
    "Driver",
    "Stint",
    "Compound",
]

TEMP_KEY_COLUMNS = [
    "_key_GP",
    "_key_Driver",
    "_key_Stint",
    "_key_Compound",
]


# ============================================================
# HELPER: NORMALIZE MATCHING KEYS
# ============================================================

def prepare_keys(df):
    """
    Create temporary matching keys without modifying the
    original feature columns.

    Text keys are stripped of surrounding whitespace.
    Stint is converted to a numeric representation.
    """

    df = df.copy()

    for col in ["GP", "Driver", "Compound"]:
        df[f"_key_{col}"] = (
            df[col].astype("string").str.strip()
        )

    df["_key_Stint"] = pd.to_numeric(
        df["Stint"],
        errors="coerce"
    )

    return df


# ============================================================
# HELPER: BUILD CORRECTED TARGET
# ============================================================

def prepare_corrected_dataset(season, paths):
    print("\n" + "=" * 65)
    print(f"PROCESSING SEASON {season}")
    print("=" * 65)

    # --------------------------------------------------------
    # 1. Load lap-level source and existing master dataset
    # --------------------------------------------------------

    source = pd.read_csv(
        paths["source"],
        low_memory=False
    )

    master = pd.read_csv(
        paths["master"],
        low_memory=False
    )

    print("Source shape:", source.shape)
    print("Existing master shape:", master.shape)

    # --------------------------------------------------------
    # 2. Validate required columns
    # --------------------------------------------------------

    source_required = (
        KEY_COLUMNS + ["LapNumber"]
    )

    missing_source = [
        col for col in source_required
        if col not in source.columns
    ]

    master_required = KEY_COLUMNS + ["StintLength"]

    missing_master = [
        col for col in master_required
        if col not in master.columns
    ]

    if missing_source:
        raise ValueError(
            f"{season}: Missing source columns: "
            f"{missing_source}"
        )

    if missing_master:
        raise ValueError(
            f"{season}: Missing master columns: "
            f"{missing_master}"
        )

    # --------------------------------------------------------
    # 3. Identify the race-session column
    # --------------------------------------------------------

    if "SessionType" in source.columns:
        session_col = "SessionType"
    elif "Session" in source.columns:
        session_col = "Session"
    else:
        raise ValueError(
            f"{season}: No SessionType or Session column found."
        )

    source = source[
        source[session_col]
        .astype("string")
        .str.strip()
        .str.upper()
        .eq("R")
    ].copy()

    # --------------------------------------------------------
    # 4. Prepare LapNumber and remove rows without valid laps
    # --------------------------------------------------------

    source["LapNumber"] = pd.to_numeric(
        source["LapNumber"],
        errors="coerce"
    )

    missing_lap_count = source["LapNumber"].isna().sum()

    source = source[
        source["LapNumber"].notna()
    ].copy()

    print("Race-session rows:", len(source))
    print("Rows excluded for missing LapNumber:", missing_lap_count)

    # --------------------------------------------------------
    # 5. Normalize matching keys
    # --------------------------------------------------------

    source = prepare_keys(source)
    master_keys = prepare_keys(master)

    # --------------------------------------------------------
    # 6. Calculate the corrected target
    #
    # Keep the existing stint grouping.
    #
    # StintLength = number of distinct observed race laps.
    # --------------------------------------------------------

    corrected_targets = (
        source.groupby(
            TEMP_KEY_COLUMNS,
            dropna=False,
            observed=True
        )
        .agg(
            CorrectedStintLength=(
                "LapNumber",
                "nunique"
            )
        )
        .reset_index()
    )

    # --------------------------------------------------------
    # 7. Ensure the existing master has one row per group
    # --------------------------------------------------------

    duplicate_mask = master_keys.duplicated(
        subset=TEMP_KEY_COLUMNS,
        keep=False
    )

    if duplicate_mask.any():
        duplicate_examples = master_keys.loc[
            duplicate_mask,
            KEY_COLUMNS
        ].head(10)

        raise ValueError(
            f"{season}: Duplicate stint keys found in master.\n"
            f"{duplicate_examples.to_string(index=False)}"
        )

    # --------------------------------------------------------
    # 8. Match targets to existing master rows
    # --------------------------------------------------------

    master_keys["_original_row_order"] = np.arange(
        len(master_keys)
    )

    merged = master_keys.merge(
        corrected_targets,
        on=TEMP_KEY_COLUMNS,
        how="left",
        validate="one_to_one",
        indicator=True
    )

    unmatched = merged["_merge"].ne("both")

    if unmatched.any():
        unmatched_rows = merged.loc[
            unmatched,
            KEY_COLUMNS
        ].head(20)

        raise ValueError(
            f"{season}: {int(unmatched.sum())} master rows "
            "could not be matched to source targets.\n"
            "No corrected file has been saved for this season.\n"
            f"{unmatched_rows.to_string(index=False)}"
        )

    # --------------------------------------------------------
    # 9. Calculate the impact of the target correction
    # --------------------------------------------------------

    old_target = pd.to_numeric(
        merged["StintLength"],
        errors="coerce"
    )

    new_target = merged["CorrectedStintLength"]

    changed_mask = ~np.isclose(
        old_target.to_numpy(dtype=float),
        new_target.to_numpy(dtype=float),
        equal_nan=True
    )

    # --------------------------------------------------------
    # 10. Replace ONLY StintLength
    # --------------------------------------------------------

    merged = merged.sort_values(
        "_original_row_order"
    )

    corrected_master = master.copy()

    corrected_master["StintLength"] = (
        merged["CorrectedStintLength"].to_numpy()
    )

    # Preserve the original feature columns and their ordering.
    assert corrected_master.columns.tolist() == (
        master.columns.tolist()
    )

    # Verify that all other columns remain identical.
    unchanged_columns = [
        col for col in master.columns
        if col != "StintLength"
    ]

    pd.testing.assert_frame_equal(
        corrected_master[unchanged_columns],
        master[unchanged_columns],
        check_dtype=True
    )

    # --------------------------------------------------------
    # 11. Report results
    # --------------------------------------------------------

    print("\nTARGET CORRECTION SUMMARY")
    print("Existing stint records:", len(master))
    print("Corrected stint records:", len(corrected_master))
    print("Unmatched master records:", int(unmatched.sum()))
    print("Targets changed:", int(changed_mask.sum()))
    print(
        "Targets unchanged:",
        int((~changed_mask).sum())
    )

    print("\nOriginal target statistics:")
    print(old_target.describe().to_string())

    print("\nCorrected target statistics:")
    print(new_target.describe().to_string())

    # Return without saving yet. All seasons must pass validation.
    return {
        "season": season,
        "master": master,
        "corrected_master": corrected_master,
        "output_path": paths["output"],
        "changed_targets": int(changed_mask.sum()),
    }


# ============================================================
# PROCESS ALL SEASONS
# ============================================================

results = {}

for season, paths in SEASONS.items():
    results[season] = prepare_corrected_dataset(
        season,
        paths
    )


# ============================================================
# SAVE ONLY AFTER ALL THREE SEASONS PASS VALIDATION
# ============================================================

for season, result in results.items():

    result["corrected_master"].to_csv(
        result["output_path"],
        index=False
    )

    print(
        f"\n{season} corrected dataset saved to:\n"
        f"{result['output_path']}"
    )


print("\n" + "=" * 65)
print("ALL THREE SEASONS PROCESSED SUCCESSFULLY")
print("Only StintLength was changed.")
print("All other master features were preserved.")
print("=" * 65)

=================================================================
PROCESSING SEASON 2023
=================================================================
Source shape: (39877, 26)
Existing master shape: (1198, 17)
Race-session rows: 22481
Rows excluded for missing LapNumber: 0

TARGET CORRECTION SUMMARY
Existing stint records: 1198
Corrected stint records: 1198
Unmatched master records: 0
Targets changed: 417
Targets unchanged: 781

Original target statistics:
count    1198.000000
mean       19.899833
std        11.135453
min         1.000000
25%        13.000000
50%        19.000000
75%        26.000000
max        58.000000

Corrected target statistics:
count    1198.000000
mean       18.765442
std        11.151913
min         1.000000
25%        11.000000
50%        18.000000
75%        25.000000
max        58.000000

=================================================================
PROCESSING SEASON 2024
=================================================================
Source shape: (40412, 26)
Existing master shape: (1229, 17)
Race-session rows: 26162
Rows excluded for missing LapNumber: 0

TARGET CORRECTION SUMMARY
Existing stint records: 1229
Corrected stint records: 1229
Unmatched master records: 0
Targets changed: 353
Targets unchanged: 876

Original target statistics:
count    1229.000000
mean       21.991863
std        11.966427
min         1.000000
25%        13.000000
50%        21.000000
75%        29.000000
max        78.000000

Corrected target statistics:
count    1229.000000
mean       21.287225
std        11.934526
min         1.000000
25%        13.000000
50%        20.000000
75%        28.000000
max        76.000000

=================================================================
PROCESSING SEASON 2025
=================================================================
Source shape: (50516, 29)
Existing master shape: (1228, 17)
Race-session rows: 25723
Rows excluded for missing LapNumber: 0

TARGET CORRECTION SUMMARY
Existing stint records: 1228
Corrected stint records: 1228
Unmatched master records: 0
Targets changed: 432
Targets unchanged: 796

Original target statistics:
count    1228.000000
mean       22.698697
std        11.309404
min         0.000000
25%        14.000000
50%        23.000000
75%        30.000000
max        72.000000

Corrected target statistics:
count    1228.000000
mean       20.947068
std        11.723435
min         1.000000
25%        12.000000
50%        21.000000
75%        28.000000
max        72.000000

2023 corrected dataset saved to:
C:/Users/VANSH/Formula1/datasets/2023/master_stint_2023_v4_targetfix.csv

2024 corrected dataset saved to:
C:/Users/VANSH/Formula1/datasets/2024/master_stint_2024_v4_targetfix.csv

2025 corrected dataset saved to:
C:/Users/VANSH/Formula1/datasets/2025/master_stint_2025_v2_targetfix.csv

=================================================================
ALL THREE SEASONS PROCESSED SUCCESSFULLY
Only StintLength was changed.
All other master features were preserved.
=================================================================

In [2]:
import pandas as pd
import joblib
from pathlib import Path

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error

from xgboost import XGBRegressor


# --------------------------------------------------
# 1. Load the three seasonal datasets
# --------------------------------------------------

stint_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/master_stint_2023_v3.csv"
)

stint_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/master_stint_2024_v3.csv"
)

stint_2025 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2025/master_stint_2025_v1.csv"
)


# --------------------------------------------------
# 2. Add Season and combine
# --------------------------------------------------

stint_2023["Season"] = 2023
stint_2024["Season"] = 2024
stint_2025["Season"] = 2025

df = pd.concat(
    [stint_2023, stint_2024, stint_2025],
    ignore_index=True
)

print("Combined shape:", df.shape)
print("\nStints by season:")
print(df["Season"].value_counts().sort_index())

print("\nMissing values in metadata:")
print(df[[
    "CircuitType",
    "TrackAbrasiveness",
    "TrackLength",
    "AverageCornerSpeed"
]].isna().sum())


# --------------------------------------------------
# 3. Define features and target
# --------------------------------------------------

categorical_features = [
    "Compound",
    "GP",
    "CircuitType",
    "TrackAbrasiveness"
]

numerical_features = [
    "AirTemp",
    "TrackTemp",
    "TrackLength",
    "Season",
    "RaceProgress",
    "FreshTyre",
    "YellowLaps",
    "SCLaps",
    "VSCLaps",
    "RedFlagLaps",
    "AverageCornerSpeed"
]

feature_columns = categorical_features + numerical_features

X = df[feature_columns].copy()
y = df["StintLength"].copy()


# Handle missing categorical metadata without guessing its value.
# Numeric missing values are left untouched.
X[categorical_features] = (
    X[categorical_features].fillna("Unknown")
)


# --------------------------------------------------
# 4. Preprocessing
# --------------------------------------------------

preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numerical_features
        )
    ]
)


# --------------------------------------------------
# 5. Train-test split
# --------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("\nTraining samples:", len(X_train))
print("Testing samples:", len(X_test))


# --------------------------------------------------
# 6. Train XGBoost
# --------------------------------------------------

model = XGBRegressor(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", model)
])

pipeline.fit(X_train, y_train)


# --------------------------------------------------
# 7. Evaluate
# --------------------------------------------------

train_predictions = pipeline.predict(X_train)
test_predictions = pipeline.predict(X_test)

train_mae = mean_absolute_error(
    y_train, train_predictions
)

test_mae = mean_absolute_error(
    y_test, test_predictions
)

print("\n========== THREE-SEASON MODEL RESULTS ==========")
print(f"Training MAE: {train_mae:.4f} laps")
print(f"Testing MAE:  {test_mae:.4f} laps")
print("================================================")


# --------------------------------------------------
# 8. Save the model
# --------------------------------------------------

model_path = Path(
    "C:/Users/VANSH/Formula1/models/xgb_stint_model_3seasons.pkl"
)

model_path.parent.mkdir(parents=True, exist_ok=True)

joblib.dump(pipeline, model_path)

print("\nModel saved to:", model_path)

Combined shape: (3655, 18)

Stints by season:
Season
2023    1198
2024    1229
2025    1228
Name: count, dtype: int64

Missing values in metadata:
CircuitType           99
TrackAbrasiveness     99
TrackLength           99
AverageCornerSpeed    99
dtype: int64

Training samples: 2924
Testing samples: 731

========== THREE-SEASON MODEL RESULTS ==========
Training MAE: 2.2520 laps
Testing MAE:  4.1372 laps
================================================

Model saved to: C:\Users\VANSH\Formula1\models\xgb_stint_model_3seasons.pkl

In [3]:
import pandas as pd
import joblib
from pathlib import Path

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error

from xgboost import XGBRegressor


# --------------------------------------------------
# 1. Load the three seasonal datasets
# --------------------------------------------------

stint_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/master_stint_2023_v4_targetfix.csv"
)

stint_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/master_stint_2024_v4_targetfix.csv"
)

stint_2025 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2025/master_stint_2025_v2_targetfix.csv"
)


# --------------------------------------------------
# 2. Add Season and combine
# --------------------------------------------------

stint_2023["Season"] = 2023
stint_2024["Season"] = 2024
stint_2025["Season"] = 2025

df = pd.concat(
    [stint_2023, stint_2024, stint_2025],
    ignore_index=True
)

print("Combined shape:", df.shape)
print("\nStints by season:")
print(df["Season"].value_counts().sort_index())

print("\nMissing values in metadata:")
print(df[[
    "CircuitType",
    "TrackAbrasiveness",
    "TrackLength",
    "AverageCornerSpeed"
]].isna().sum())


# --------------------------------------------------
# 3. Define features and target
# --------------------------------------------------

categorical_features = [
    "Compound",
    "GP",
    "CircuitType",
    "TrackAbrasiveness"
]

numerical_features = [
    "AirTemp",
    "TrackTemp",
    "TrackLength",
    "Season",
    "RaceProgress",
    "FreshTyre",
    "YellowLaps",
    "SCLaps",
    "VSCLaps",
    "RedFlagLaps",
    "AverageCornerSpeed"
]

feature_columns = categorical_features + numerical_features

X = df[feature_columns].copy()
y = df["StintLength"].copy()


# Handle missing categorical metadata without guessing its value.
# Numeric missing values are left untouched.
X[categorical_features] = (
    X[categorical_features].fillna("Unknown")
)


# --------------------------------------------------
# 4. Preprocessing
# --------------------------------------------------

preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numerical_features
        )
    ]
)


# --------------------------------------------------
# 5. Train-test split
# --------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("\nTraining samples:", len(X_train))
print("Testing samples:", len(X_test))


# --------------------------------------------------
# 6. Train XGBoost
# --------------------------------------------------

model = XGBRegressor(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", model)
])

pipeline.fit(X_train, y_train)


# --------------------------------------------------
# 7. Evaluate
# --------------------------------------------------

train_predictions = pipeline.predict(X_train)
test_predictions = pipeline.predict(X_test)

train_mae = mean_absolute_error(
    y_train, train_predictions
)

test_mae = mean_absolute_error(
    y_test, test_predictions
)

print("\n========== THREE-SEASON MODEL RESULTS ==========")
print(f"Training MAE: {train_mae:.4f} laps")
print(f"Testing MAE:  {test_mae:.4f} laps")
print("================================================")


# --------------------------------------------------
# 8. Save the model
# --------------------------------------------------

model_path = Path(
    "C:/Users/VANSH/Formula1/models/xgb_stint_model_3seasons.pkl"
)

model_path.parent.mkdir(parents=True, exist_ok=True)

joblib.dump(pipeline, model_path)

print("\nModel saved to:", model_path)

Combined shape: (3655, 18)

Stints by season:
Season
2023    1198
2024    1229
2025    1228
Name: count, dtype: int64

Missing values in metadata:
CircuitType           99
TrackAbrasiveness     99
TrackLength           99
AverageCornerSpeed    99
dtype: int64

Training samples: 2924
Testing samples: 731

========== THREE-SEASON MODEL RESULTS ==========
Training MAE: 2.1602 laps
Testing MAE:  3.8611 laps
================================================

Model saved to: C:\Users\VANSH\Formula1\models\xgb_stint_model_3seasons.pkl

#### 5-fold Validation on new target stint logic

In [4]:
import pandas as pd
import numpy as np

from xgboost import XGBRegressor

from sklearn.model_selection import KFold, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer


# ============================================================
# STEP 1: LOAD THE THREE CORRECTED MASTER DATASETS
# ============================================================

df_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/"
    "master_stint_2023_v4_targetfix.csv"
)

df_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/"
    "master_stint_2024_v4_targetfix.csv"
)

df_2025 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2025/"
    "master_stint_2025_v2_targetfix.csv"
)

# Add season labels
df_2023["Season"] = 2023
df_2024["Season"] = 2024
df_2025["Season"] = 2025

# Combine all seasons
df = pd.concat(
    [df_2023, df_2024, df_2025],
    ignore_index=True
)

print("Combined shape:", df.shape)

print("\nStints by season:")
print(df["Season"].value_counts().sort_index())


# ============================================================
# STEP 2: DEFINE FEATURES AND TARGET
# ============================================================

target = "StintLength"

categorical_features = [
    "GP",
    "Compound",
    "CircuitType",
    "TrackAbrasiveness"
]

numerical_features = [
    "AirTemp",
    "TrackTemp",
    "TrackLength",
    "Season",
    "RaceProgress",
    "FreshTyre",
    "YellowLaps",
    "SCLaps",
    "VSCLaps",
    "RedFlagLaps",
    "AverageCornerSpeed"
]

features = categorical_features + numerical_features

# Validate required columns
required_columns = features + [target]

missing_columns = [
    col for col in required_columns
    if col not in df.columns
]

if missing_columns:
    raise ValueError(
        f"Missing required columns: {missing_columns}"
    )

# Keep only model features and target
model_data = df[required_columns].copy()

# Ensure the target is numeric
model_data[target] = pd.to_numeric(
    model_data[target],
    errors="coerce"
)

# Remove rows without a valid target
model_data = model_data.dropna(
    subset=[target]
).reset_index(drop=True)

X = model_data[features]
y = model_data[target]

print("\nModel dataset shape:", model_data.shape)
print("Feature count:", len(features))
print("Missing target values:", y.isna().sum())


# ============================================================
# STEP 3: PREPROCESSING
# ============================================================

# Numerical columns:
# Replace missing values with the training-fold median.
numerical_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="median")
        )
    ]
)

# Categorical columns:
# Replace missing values with the most frequent category,
# then one-hot encode categorical variables.
categorical_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="most_frequent")
        ),
        (
            "encoder",
            OneHotEncoder(
                handle_unknown="ignore"
            )
        )
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        (
            "numerical",
            numerical_pipeline,
            numerical_features
        ),
        (
            "categorical",
            categorical_pipeline,
            categorical_features
        )
    ]
)


# ============================================================
# STEP 4: DEFINE XGBOOST MODEL
# ============================================================

xgb_model = XGBRegressor(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    objective="reg:squarederror",
    n_jobs=-1
)


# ============================================================
# STEP 5: BUILD THE COMPLETE PIPELINE
# ============================================================

model_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", xgb_model)
    ]
)


# ============================================================
# STEP 6: CONFIGURE 5-FOLD CROSS-VALIDATION
# ============================================================

kf = KFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

# sklearn returns negative MAE because its scoring convention
# treats higher scores as better.
cv_scores = cross_val_score(
    model_pipeline,
    X,
    y,
    cv=kf,
    scoring="neg_mean_absolute_error",
    n_jobs=1
)

# Convert negative MAE to positive MAE
fold_mae = -cv_scores


# ============================================================
# STEP 7: DISPLAY RESULTS
# ============================================================

print("\n" + "=" * 50)
print("5-FOLD CROSS-VALIDATION RESULTS")
print("=" * 50)

for fold_number, mae in enumerate(fold_mae, start=1):
    print(f"Fold {fold_number} MAE: {mae:.4f} laps")

mean_mae = fold_mae.mean()
std_mae = fold_mae.std(ddof=1)
min_mae = fold_mae.min()
max_mae = fold_mae.max()

print("-" * 50)
print(f"Mean CV MAE: {mean_mae:.4f} laps")
print(f"Standard deviation: {std_mae:.4f} laps")
print(f"Best fold MAE: {min_mae:.4f} laps")
print(f"Worst fold MAE: {max_mae:.4f} laps")
print("=" * 50)

Combined shape: (3655, 18)

Stints by season:
Season
2023    1198
2024    1229
2025    1228
Name: count, dtype: int64

Model dataset shape: (3655, 16)
Feature count: 15
Missing target values: 0

==================================================
5-FOLD CROSS-VALIDATION RESULTS
==================================================
Fold 1 MAE: 3.8599 laps
Fold 2 MAE: 3.6014 laps
Fold 3 MAE: 3.5623 laps
Fold 4 MAE: 3.9519 laps
Fold 5 MAE: 3.8446 laps
--------------------------------------------------
Mean CV MAE: 3.7640 laps
Standard deviation: 0.1718 laps
Best fold MAE: 3.5623 laps
Worst fold MAE: 3.9519 laps
==================================================

In [5]:
import pandas as pd
import numpy as np

from sklearn.model_selection import GroupKFold, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from xgboost import XGBRegressor


# ============================================================
# 1. LOAD THE CORRECTED DATASETS
# ============================================================

df_2023 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2023/master_stint_2023_v4_targetfix.csv"
)

df_2024 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2024/master_stint_2024_v4_targetfix.csv"
)

df_2025 = pd.read_csv(
    "C:/Users/VANSH/Formula1/datasets/2025/master_stint_2025_v2_targetfix.csv"
)

# Explicitly assign seasons to identify individual race weekends.
df_2023["Season"] = 2023
df_2024["Season"] = 2024
df_2025["Season"] = 2025

df = pd.concat(
    [df_2023, df_2024, df_2025],
    ignore_index=True
)

print("Combined dataset shape:", df.shape)


# ============================================================
# 2. DEFINE FEATURES AND TARGET
# ============================================================

categorical_features = [
    "Compound",
    "GP",
    "CircuitType",
    "TrackAbrasiveness"
]

numerical_features = [
    "AirTemp",
    "TrackTemp",
    "TrackLength",
    "Season",
    "RaceProgress",
    "FreshTyre",
    "YellowLaps",
    "SCLaps",
    "VSCLaps",
    "RedFlagLaps",
    "AverageCornerSpeed"
]

features = categorical_features + numerical_features

X = df[features]
y = df["StintLength"]

# Each race weekend gets a unique group, including its season.
# For example, Bahrain 2023 and Bahrain 2025 are separate events.
groups = (
    df["Season"].astype(str)
    + "_"
    + df["GP"].astype(str)
)

print("Unique race weekends:", groups.nunique())


# ============================================================
# 3. PREPROCESSING
# ============================================================

numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", numeric_transformer, numerical_features),
    ("cat", categorical_transformer, categorical_features)
])


# ============================================================
# 4. XGBOOST MODEL
# ============================================================

model = XGBRegressor(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", model)
])


# ============================================================
# 5. GROUP K-FOLD CROSS-VALIDATION
# ============================================================

gkf = GroupKFold(n_splits=5)

scores = cross_val_score(
    pipeline,
    X,
    y,
    groups=groups,
    cv=gkf,
    scoring="neg_mean_absolute_error",
    n_jobs=1
)

mae_scores = -scores

print("\n========== GROUP K-FOLD RESULTS ==========")

for fold, mae in enumerate(mae_scores, start=1):
    print(f"Fold {fold} MAE: {mae:.4f}")

print("------------------------------------------")
print(f"Mean MAE: {mae_scores.mean():.4f}")
print(f"Standard Deviation: {mae_scores.std(ddof=1):.4f}")
print(f"Best Fold MAE: {mae_scores.min():.4f}")
print(f"Worst Fold MAE: {mae_scores.max():.4f}")
print("==========================================")

Combined dataset shape: (3655, 18)
Unique race weekends: 69

========== GROUP K-FOLD RESULTS ==========
Fold 1 MAE: 8.1880
Fold 2 MAE: 7.8398
Fold 3 MAE: 8.6725
Fold 4 MAE: 7.2455
Fold 5 MAE: 8.4144
------------------------------------------
Mean MAE: 8.0720
Standard Deviation: 0.5542
Best Fold MAE: 7.2455
Worst Fold MAE: 8.6725
==========================================